(function(g){var window=this;var VGa=function(a,b){return g.Ob(a,b)},j4=function(a,b,c){a.C.set(b,c)},k4=function(a){j4(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.A()).toString(36));
return a},l4=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.cn(a.C,b,c)},WGa=function(a,b){var c=[];
g.jj(b,function(d){try{var e=g.ao.prototype.B.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.$n(e)&&c.push(d)},a);
return c},XGa=function(a,b){var c=WGa(a,b);
g.Cb(c,function(d){g.ao.prototype.remove.call(this,d)},a)},YGa=function(a){if(a.U){if(a.U.locationOverrideToken)return{locationOverrideToken:a.U.locationOverrideToken};
if(null!=a.U.latitudeE7&&null!=a.U.longitudeE7)return{latitudeE7:a.U.latitudeE7,longitudeE7:a.U.longitudeE7}}return null},ZGa=function(a,b){g.ib(a,b)||a.push(b)},m4=function(a){var b=0,c;
for(c in a)b++;return b},$Ga=function(a,b){var c=b instanceof g.Ec?b:g.Kc(b,/^data:image\//i.test(b));
a.src=g.Fc(c)},n4=function(){},aHa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},bHa=function(a){if(a.Yf&&"function"==typeof a.Yf)return a.Yf();
if("string"===typeof a)return a.split("");if(g.Oa(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Kb(a)},cHa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Oa(a)||"string"===typeof a)g.Cb(a,b,void 0);else{if(a.sh&&"function"==typeof a.sh)var c=a.sh();else if(a.Yf&&"function"==typeof a.Yf)c=void 0;else if(g.Oa(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Lb(a);d=bHa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},dHa=function(a,b,c,d){var e=new g.Rm(null,void 0);
a&&g.Sm(e,a);b&&g.Tm(e,b);c&&g.Um(e,c);d&&(e.B=d);return e},o4=function(a,b){g.Ko[a]=!0;
var c=g.Io();c&&c.publish.apply(c,arguments);g.Ko[a]=!1},p4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Om;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",eHa(this,a.capabilities||""),fHa(this,a.experiments||""))},eHa=function(a,b){a.capabilities.clear();
g.Me(b.split(","),g.Sa(VGa,gHa)).forEach(function(c){a.capabilities.add(c)})},fHa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},q4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||"";this.idType=a.screenIdType||"normal"},r4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},hHa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid,screenIdType:a.idType}},iHa=function(a){return new q4(a)},jHa=function(a){return Array.isArray(a)?g.Oc(a,iHa):[]},s4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+((a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+",idType:"+a.idType+"}"):"null"},t4=function(a){return Array.isArray(a)?"["+g.Oc(a,s4).join(",")+"]":"null"},u4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},kHa=function(a){return g.Oc(a,function(b){return{key:b.id,
name:b.name}})},v4=function(a,b){return g.eb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},w4=function(a,b){return g.eb(a,function(c){return r4(c,b)})},lHa=function(){var a=(0,g.ru)();
a&&XGa(a,a.u.Yj(!0))},x4=function(){var a=g.vu("yt-remote-connected-devices")||[];
g.zb(a);return a},mHa=function(a){if(g.jb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Oc(a,function(d,e){return 0==e?d:d.substring(c.length)})},nHa=function(a){g.uu("yt-remote-connected-devices",a,86400)},z4=function(){if(y4)return y4;
var a=g.vu("yt-remote-device-id");a||(a=u4(),g.uu("yt-remote-device-id",a,31536E3));for(var b=x4(),c=1,d=a;g.ib(b,d);)c++,d=a+"#"+c;return y4=d},A4=function(){var a=x4(),b=z4();
g.ib(a,b);g.xu()&&g.Bb(a,b);a=mHa(a);if(g.jb(a))try{g.Cq("remote_sid")}catch(c){}else try{g.Aq("remote_sid",a.join(","),-1)}catch(c){}},oHa=function(){return g.vu("yt-remote-session-browser-channel")},pHa=function(){return g.vu("yt-remote-local-screens")||[]},qHa=function(){g.uu("yt-remote-lounge-token-expiration",!0,86400)},rHa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Oc(pHa(),function(d){return d.loungeToken}),c=g.Oc(a,function(d){return d.loungeToken});
g.sh(c,function(d){return!g.ib(b,d)})&&qHa();
g.uu("yt-remote-local-screens",a,31536E3)},sHa=function(a,b){g.uu("yt-remote-session-browser-channel",a);
g.uu("yt-remote-session-screen-id",b);var c=x4(),d=z4();g.ib(c,d)||c.push(d);nHa(c);A4()},B4=function(a){a||(g.wu("yt-remote-session-screen-id"),g.wu("yt-remote-session-video-id"));
A4();a=x4();g.nb(a,z4());nHa(a)},tHa=function(){if(!C4){var a=g.lo();
a&&(C4=new g.Vn(a))}},uHa=function(){tHa();
return C4?!!C4.get("yt-remote-use-staging-server"):!1},vHa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},wHa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},D4=function(a){a.length?xHa(a.shift(),function(){D4(a)}):E4()},yHa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},xHa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.id(d,g.pg(a));(document.head||document.documentElement).appendChild(d)},E4=function(){var a=wHa();
a&&a(!1,"No cast extension found")},AHa=function(){if(zHa){var a=2,b=wHa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;xHa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",E4,c)}},BHa=function(){AHa();
var a=(a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/))?parseInt(a[1],10):0;var b=[];if(0!=a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}b.push("//www.gstatic.com/eureka/clank/cast_sender.js");D4(b)},F4=function(a,b,c){g.B.call(this);
this.I=null!=c?(0,g.z)(a,c):a;this.Kf=b;this.F=(0,g.z)(this.VJ,this);this.u=!1;this.B=0;this.C=this.fb=null;this.D=[]},G4=function(a,b,c){g.B.call(this);
this.D=null!=c?a.bind(c):a;this.Kf=b;this.C=null;this.u=!1;this.B=0;this.fb=null},H4=function(a){a.fb=g.Mm(function(){a.fb=null;
a.u&&!a.B&&(a.u=!1,H4(a))},a.Kf);
var b=a.C;a.C=null;a.D.apply(null,b)},I4=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return aHa(a)},J4=function(){},K4=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},M4=function(a){L4.dispatchEvent(new CHa(L4,a))},CHa=function(a){g.Fl.call(this,"statevent",a)},N4=function(){},DHa=function(){},FHa=function(a){return(a=EHa(a))?new ActiveXObject(a):new XMLHttpRequest},EHa=function(a){if(!a.B&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.B=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.B},O4=function(a,b,c,d){this.u=a;
this.B=b;this.L=c;this.K=d||1;this.F=45E3;this.D=new g.p_(this);this.C=new g.Lm;this.C.setInterval(250)},HHa=function(a,b,c){a.Yp=1;
a.dl=k4(b.clone());a.Hn=c;a.I=!0;GHa(a,null)},P4=function(a,b,c,d,e){a.Yp=1;
a.dl=k4(b.clone());a.Hn=null;a.I=c;e&&(a.cH=!1);GHa(a,d)},GHa=function(a,b){a.Qp=g.A();
Q4(a);a.hm=a.dl.clone();l4(a.hm,"t",a.K);a.Zs=0;a.Be=a.u.yx(a.u.Hs()?b:null);0<a.oy&&(a.tv=new G4((0,g.z)(a.XH,a,a.Be),a.oy));a.D.va(a.Be,"readystatechange",a.IQ);var c=a.nn?g.Vb(a.nn):{};a.Hn?(a.ew="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Be.send(a.hm,a.ew,a.Hn,c)):(a.ew="GET",a.cH&&!g.Be&&(c.Connection="close"),a.Be.send(a.hm,a.ew,null,c));a.u.ni(1)},KHa=function(a,b,c){for(var d=!0;!a.Vm&&a.Zs<c.length;){var e=IHa(a,c);
if(e==R4){4==b&&(a.El=4,M4(15),d=!1);break}else if(e==JHa){a.El=4;M4(16);d=!1;break}else S4(a,e)}4==b&&0==c.length&&(a.El=1,M4(17),d=!1);a.Ei=a.Ei&&d;d||(T4(a),U4(a))},IHa=function(a,b){var c=a.Zs,d=b.indexOf("\n",c);
if(-1==d)return R4;c=Number(b.substring(c,d));if(isNaN(c))return JHa;d+=1;if(d+c>b.length)return R4;var e=b.substr(d,c);a.Zs=d+c;return e},MHa=function(a,b){a.Qp=g.A();
Q4(a);var c=b?window.location.hostname:"";a.hm=a.dl.clone();j4(a.hm,"DOMAIN",c);j4(a.hm,"t",a.K);try{a.Ii=new ActiveXObject("htmlfile")}catch(n){T4(a);a.El=7;M4(22);U4(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var h=c.charAt(f);if("<"==h)h=e+"\\x3c";else if(">"==h)h=e+"\\x3e";else{if(h in V4)h=V4[h];else if(h in LHa)h=V4[h]=LHa[h];else{var l=h.charCodeAt(0);if(31<l&&127>l)var m=h;else{if(256>l){if(m="\\x",16>l||256<l)m+="0"}else m="\\u",4096>l&&(m+="0");m+=l.toString(16).toUpperCase()}h=
V4[h]=m}h=e+h}e=h}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.fd(g.hc("b/12014412"),d+"</body></html>");a.Ii.open();a.Ii.write(g.bd(c));a.Ii.close();a.Ii.parentWindow.m=(0,g.z)(a.bQ,a);a.Ii.parentWindow.d=(0,g.z)(a.lG,a,!0);a.Ii.parentWindow.rpcClose=(0,g.z)(a.lG,a,!1);c=a.Ii.createElement("DIV");a.Ii.parentWindow.document.body.appendChild(c);d=g.Jc(a.hm.toString());d=g.md(g.Fc(d));d=g.fd(g.hc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.gd(c,d);a.u.ni(1)},Q4=function(a){a.YA=g.A()+a.F;
NHa(a,a.F)},NHa=function(a,b){if(null!=a.fq)throw Error("WatchDog timer not null");
a.fq=K4((0,g.z)(a.iQ,a),b)},W4=function(a){a.fq&&(g.v.clearTimeout(a.fq),a.fq=null)},U4=function(a){a.u.pD()||a.Vm||a.u.cu(a)},T4=function(a){W4(a);
g.ag(a.tv);a.tv=null;a.C.stop();g.mBa(a.D);if(a.Be){var b=a.Be;a.Be=null;b.abort();b.dispose()}a.Ii&&(a.Ii=null)},S4=function(a,b){try{a.u.dG(a,b),a.u.ni(4)}catch(c){}},PHa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;OHa(a,b,function(h){h?c(!0):g.v.setTimeout(function(){PHa(a,b,c,d,f)},f)})}},OHa=function(a,b,c){var d=new Image;
d.onload=function(){try{X4(d),c(!0)}catch(e){}};
d.onerror=function(){try{X4(d),c(!1)}catch(e){}};
d.onabort=function(){try{X4(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{X4(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
$Ga(d,a)},X4=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},Y4=function(a){g.bm.call(this);
this.headers=new g.Om;this.da=a||null;this.C=!1;this.ba=this.u=null;this.xa=this.U="";this.I=0;this.D="";this.F=this.ka=this.L=this.ga=!1;this.K=0;this.W=null;this.za="";this.X=this.ea=!1},QHa=function(a){return g.ze&&g.$d(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},RHa=function(a){return"content-type"==a.toLowerCase()},THa=function(a,b){a.C=!1;
a.u&&(a.F=!0,a.u.abort(),a.F=!1);a.D=b;a.I=5;SHa(a);Z4(a)},SHa=function(a){a.ga||(a.ga=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},VHa=function(a){if(a.C&&"undefined"!=typeof g.u_)if(a.ba[1]&&4==$4(a)&&2==a.getStatus())a5(a,"Local request error detected and ignored");
else if(a.L&&4==$4(a))g.Mm(a.aG,0,a);else if(a.dispatchEvent("readystatechange"),a.isComplete()){a5(a,"Request complete");a.C=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.vd(1,String(a.U));if(!f&&g.v.self&&g.v.self.location){var h=g.v.self.location.protocol;f=h.substr(0,h.length-1)}e=!UHa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.I=6;try{var l=2<$4(a)?a.u.statusText:""}catch(m){l=""}a.D=l+" ["+a.getStatus()+"]";SHa(a)}}finally{Z4(a)}}},Z4=function(a,b){if(a.u){WHa(a);
var c=a.u,d=a.ba[0]?g.Ka:null;a.u=null;a.ba=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},WHa=function(a){a.u&&a.X&&(a.u.ontimeout=null);
a.W&&(g.v.clearTimeout(a.W),a.W=null)},$4=function(a){return a.u?a.u.readyState:0},b5=function(a){try{return a.u?a.u.responseText:""}catch(b){return""}},a5=function(a,b){return b+" ["+a.xa+" "+a.U+" "+a.getStatus()+"]"},XHa=function(a){this.u=a;
this.B=new J4},YHa=function(a){var b=c5(a.u,a.tq,"/mail/images/cleardot.gif");
k4(b);PHa(b.toString(),5E3,(0,g.z)(a.XI,a),3,2E3);a.ni(1)},e5=function(a){var b=a.u.L;
if(null!=b)M4(5),b?(M4(11),d5(a.u,a,!1)):(M4(12),d5(a.u,a,!0));else if(a.Gg=new O4(a,void 0,void 0,void 0),a.Gg.nn=a.my,b=a.u,b=c5(b,b.Hs()?a.mr:null,a.ny),M4(5),!g.ze||g.ae(10))l4(b,"TYPE","xmlhttp"),P4(a.Gg,b,!1,a.mr,!1);else{l4(b,"TYPE","html");var c=a.Gg;a=!!a.mr;c.Yp=3;c.dl=k4(b.clone());MHa(c,a)}},f5=function(a,b,c){this.Ja=1;
this.u=[];this.C=[];this.D=new J4;this.K=a||null;this.L=null!=b?b:null;this.F=c||!1},ZHa=function(a,b){this.u=a;
this.map=b;this.context=null},$Ha=function(a,b,c,d){g.Fl.call(this,"timingevent",a);
this.size=b;this.As=d},aIa=function(a){g.Fl.call(this,"serverreachability",a)},dIa=function(a){bIa(a);
if(3==a.Ja){var b=a.Vr++,c=a.Et.clone();j4(c,"SID",a.B);j4(c,"RID",b);j4(c,"TYPE","terminate");g5(a,c);b=new O4(a,a.B,b,void 0);b.Yp=2;b.dl=k4(c.clone());$Ga(new Image,b.dl.toString());b.Qp=g.A();Q4(b)}cIa(a)},eIa=function(a){a.tJ(1,0);
a.Et=c5(a,null,a.ly);h5(a)},bIa=function(a){a.kl&&(a.kl.abort(),a.kl=null);
a.ae&&(a.ae.cancel(),a.ae=null);a.ak&&(g.v.clearTimeout(a.ak),a.ak=null);i5(a);a.sg&&(a.sg.cancel(),a.sg=null);a.sl&&(g.v.clearTimeout(a.sl),a.sl=null)},fIa=function(a,b){if(0==a.Ja)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new ZHa(a.bN++,b));2!=a.Ja&&3!=a.Ja||h5(a)},gIa=function(a){var b=0;
a.ae&&b++;a.sg&&b++;return b},h5=function(a){a.sg||a.sl||(a.sl=K4((0,g.z)(a.kG,a),0),a.Lo=0)},iIa=function(a,b){if(1==a.Ja){if(!b){a.Vr=Math.floor(1E5*Math.random());
var c=a.Vr++,d=new O4(a,"",c,void 0);d.nn=a.oj;var e=j5(a),f=a.Et.clone();j4(f,"RID",c);j4(f,"CVER","1");g5(a,f);HHa(d,f,e);a.sg=d;a.Ja=2}}else 3==a.Ja&&(b?hIa(a,b):0==a.u.length||a.sg||hIa(a))},hIa=function(a,b){if(b)if(6<a.Wm){a.u=a.C.concat(a.u);
a.C.length=0;var c=a.Vr-1;var d=j5(a)}else c=b.L,d=b.Hn;else c=a.Vr++,d=j5(a);var e=a.Et.clone();j4(e,"SID",a.B);j4(e,"RID",c);j4(e,"AID",a.jp);g5(a,e);c=new O4(a,a.B,c,a.Lo+1);c.nn=a.oj;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.sg=c;HHa(c,e,d)},g5=function(a,b){if(a.If){var c=a.If.SC();
c&&g.Eb(c,function(d,e){j4(b,e,d)})}},j5=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.Wm&&0<b){var d=a.u[0].u;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={ho:e.ho},f++){e.ho=a.u[f].u;var h=a.u[f].map;e.ho=6>=a.Wm?f:e.ho-d;try{g.Eb(h,function(l){return function(m,n){c.push("req"+l.ho+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.ho+"_type="+encodeURIComponent("_badmap"))}}a.C=a.C.concat(a.u.splice(0,b));
return c.join("&")},jIa=function(a){a.ae||a.ak||(a.I=1,a.ak=K4((0,g.z)(a.jG,a),0),a.vo=0)},k5=function(a){if(a.ae||a.ak||3<=a.vo)return!1;
a.I++;a.ak=K4((0,g.z)(a.jG,a),kIa(a,a.vo));a.vo++;return!0},d5=function(a,b,c){a.bw=c;
a.pj=b.tk;a.F||eIa(a)},i5=function(a){null!=a.cn&&(g.v.clearTimeout(a.cn),a.cn=null)},kIa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},l5=function(a,b){if(2==b||9==b){var c=null;
a.If&&(c=null);var d=(0,g.z)(a.rR,a);c||(c=new g.Rm("//www.google.com/images/cleardot.gif"),k4(c));OHa(c.toString(),1E4,d)}else M4(2);lIa(a,b)},lIa=function(a,b){a.Ja=0;
a.If&&a.If.fC(b);cIa(a);bIa(a)},cIa=function(a){a.Ja=0;
a.pj=-1;if(a.If)if(0==a.C.length&&0==a.u.length)a.If.ix();else{g.rb(a.C);var b=g.rb(a.u);a.C.length=0;a.u.length=0;a.If.ix(b)}},c5=function(a,b,c){var d=g.Zm(c);
if(""!=d.u)b&&g.Tm(d,b+"."+d.u),g.Um(d,d.D);else{var e=window.location;d=dHa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Nq&&g.Eb(a.Nq,function(f,h){j4(d,h,f)});
j4(d,"VER",a.Wm);g5(a,d);return d},mIa=function(){},nIa=function(){this.u=[];
this.B=[]},oIa=function(a,b){this.action=a;
this.params=b||{}},m5=function(a,b){g.B.call(this);
this.u=new g.F(this.UP,0,this);g.C(this,this.u);this.Kf=5E3;this.B=0;if("function"===typeof a)b&&(a=(0,g.z)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.C=a},n5=function(a,b,c,d,e){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
e=void 0===e?!1:e;this.ba=a;this.I=b;this.C=new g.Un;this.B=new m5(this.TQ,this);this.u=null;this.W=!1;this.F=null;this.U="";this.L=this.D=0;this.K=[];this.da=c;this.X=d;this.ga=e},pIa=function(a){return{firstTestResults:[""],
secondTestResults:!a.u.bw,sessionId:a.u.B,arrayId:a.u.jp}},qIa=function(a,b){a.L=b||0;
a.B.stop();o5(a);a.u&&(3==a.u.getState()&&iIa(a.u),dIa(a.u));a.L=0},p5=function(a){return!!a.u&&3==a.u.getState()},o5=function(a){if(a.u){var b=a.X(),c=a.u.oj||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.u.oj=c}},q5=function(a){this.scheme="https";
this.port=this.domain="";this.u="/api/lounge";this.B=!0;a=a||document.location.href;var b=Number(g.vd(4,a))||"";b&&(this.port=":"+b);this.domain=g.wd(a)||"";a=g.Vc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Cc(a,"10.0")&&(this.B=!1))},r5=function(a,b){var c=a.u;
a.B&&(c=a.scheme+"://"+a.domain+a.port+a.u);return g.Ld(c+b,{})},s5=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Sa(a.D,d,!0),onError:g.Sa(a.C,e),onTimeout:g.Sa(a.F,e)};c&&(a.postParams=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.uq(b,a)},uIa=function(){var a=rIa;
sIa();t5.push(a);tIa()},u5=function(a,b){sIa();
var c=vIa(a,String(b));g.jb(t5)?wIa(c):(tIa(),g.Cb(t5,function(d){d(c)}))},sIa=function(){t5||(t5=g.Ja("yt.mdx.remote.debug.handlers_")||[],g.Fa("yt.mdx.remote.debug.handlers_",t5,void 0))},wIa=function(a){var b=(v5+1)%50;
v5=b;w5[b]=a;x5||(x5=49==b)},tIa=function(){var a=t5;
if(w5[0]){var b=x5?v5:-1;do{b=(b+1)%50;var c=w5[b];g.Cb(a,function(d){d(c)})}while(b!=v5);
w5=Array(50);v5=-1;x5=!1}},vIa=function(a,b){var c=(g.A()-xIa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},y5=function(a){g.N.call(this);
this.I=a;this.screens=[]},yIa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},zIa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.Me(a.screens,function(f){return!!v4(b,f)});
for(var d=0,e=b.length;d<e;d++)c=yIa(a,b[d])||c;return c},AIa=function(a,b){var c=a.screens.length;
a.screens=g.Me(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},z5=function(a,b,c,d){g.N.call(this);
this.F=a;this.I=b;this.C=c;this.D=d;this.B=0;this.u=null;this.fb=NaN},B5=function(a){y5.call(this,"LocalScreenService");
this.B=a;this.u=NaN;A5(this);this.info("Initializing with "+t4(this.screens))},BIa=function(a){if(a.screens.length){var b=g.Oc(a.screens,function(d){return d.id}),c=r5(a.B,"/pairing/get_lounge_token_batch");
s5(a.B,c,{screen_ids:b.join(",")},(0,g.z)(a.dK,a),(0,g.z)(a.cK,a))}},A5=function(a){if(g.Vo("deprecate_pair_servlet_enabled"))return zIa(a,[]);
var b=jHa(pHa());b=g.Me(b,function(c){return!c.uuid});
return zIa(a,b)},C5=function(a,b){rHa(g.Oc(a.screens,hHa));
b&&qHa()},E5=function(a,b){g.N.call(this);
this.I=b;var c=g.vu("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.I(),f=0,h=e.length;f<h;++f){var l=e[f].id;d[l]=g.ib(c,l)}this.u=d;this.F=a;this.C=this.D=NaN;this.B=null;D5("Initialized with "+g.Qj(this.u))},F5=function(a,b,c){var d=r5(a.F,"/pairing/get_screen_availability");
s5(a.F,d,{lounge_token:b.token},(0,g.z)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},G5=function(a,b){a:if(m4(b)!=m4(a.u))var c=!1;
else{c=g.Lb(b);for(var d=0,e=c.length;d<e;++d)if(!a.u[c[d]]){c=!1;break a}c=!0}c||(D5("Updated online screens: "+g.Qj(a.u)),a.u=b,a.V("screenChange"));CIa(a)},H5=function(a){isNaN(a.C)||g.Ho(a.C);
a.C=g.Fo((0,g.z)(a.Zz,a),0<a.D&&a.D<g.A()?2E4:1E4)},D5=function(a){u5("OnlineScreenService",a)},DIa=function(a){var b={};
g.Cb(a.I(),function(c){c.token?b[c.token]=c.id:this.Ed("Requesting availability of screen w/o lounge token.")});
return b},CIa=function(a){a=g.Lb(g.Fb(a.u,function(b){return b}));
g.zb(a);a.length?g.uu("yt-remote-online-screen-ids",a.join(","),60):g.wu("yt-remote-online-screen-ids")},I5=function(a){y5.call(this,"ScreenService");
this.F=a;this.u=this.B=null;this.C=[];this.D={};EIa(this)},GIa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var h=a.Sg();if(h=(c?w4(h,c):null)||w4(h,b)){h.uuid=b;var l=J5(a,h);F5(a.u,l,function(m){e(m?l:null)})}else c?FIa(a,c,(0,g.z)(function(m){var n=J5(this,new q4({name:d,
screenId:c,loungeToken:m,dialId:b||""}));F5(this.u,n,function(p){e(p?n:null)})},a),f):e(null)},HIa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},IIa=function(a,b,c){F5(a.u,b,c)},FIa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={postParams:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){var l=h&&h.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.uq(r5(a.F,"/pairing/get_lounge_token_batch"),e)},JIa=function(a){a.screens=a.B.Sg();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+t4(a.screens))},EIa=function(a){K5(a);
a.B=new B5(a.F);a.B.subscribe("screenChange",(0,g.z)(a.jK,a));JIa(a);a.C=jHa(g.vu("yt-remote-automatic-screen-cache")||[]);K5(a);a.info("Initializing automatic screens: "+t4(a.C));a.u=new E5(a.F,(0,g.z)(a.Sg,a,!0));a.u.subscribe("screenChange",(0,g.z)(function(){this.V("onlineScreenChange")},a))},J5=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=w4(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),KIa(a));K5(a);a.D[b.uuid]=b.id;g.uu("yt-remote-device-id-map",a.D,31536E3);return b},KIa=function(a){a=g.Me(a.C,function(b){return"shortLived"!=b.idType});
g.uu("yt-remote-automatic-screen-cache",g.Oc(a,hHa))},K5=function(a){a.D=g.vu("yt-remote-device-id-map")||{}},L5=function(a,b,c){g.N.call(this);
this.ga=c;this.F=a;this.u=b;this.C=null},M5=function(a,b){a.C=b;
a.V("sessionScreen",a.C)},N5=function(a,b){u5(a.ga,b)},O5=function(a,b,c){L5.call(this,a,b,"CastSession");
var d=this;this.ea=c;this.B=null;this.da=(0,g.z)(this.UR,this);this.X=(0,g.z)(this.pQ,this);this.W=g.Fo(function(){LIa(d,null)},12E4);
this.K=this.D=this.I=this.L=0;this.ba=!1;this.U="unknown"},P5=function(a,b){g.Ho(a.K);
a.K=0;0==b?MIa(a):a.K=g.Fo(function(){MIa(a)},b)},MIa=function(a){NIa(a,"getLoungeToken");
g.Ho(a.D);a.D=g.Fo(function(){OIa(a,null)},3E4)},NIa=function(a,b){a.info("sendYoutubeMessage_: "+b+" "+g.Qj(void 0));
var c={};c.type=b;a.B?a.B.sendMessage("urn:x-cast:com.google.youtube.mdx",c,g.Ka,(0,g.z)(function(){N5(this,"Failed to send message: "+b+".")},a)):N5(a,"Sending yt message without session: "+g.Qj(c))},Q5=function(a,b){b?(a.info("onConnectedScreenId_: Received screenId: "+b),a.getScreen()&&a.getScreen().id==b||a.jD(b,function(c){M5(a,c)},function(){return a.hg()},5)):a.hg(Error("Waiting for session status timed out."))},QIa=function(a,b,c){a.info("onConnectedScreenData_: Received screenData: "+JSON.stringify(b));
var d=new q4(b);PIa(a,d,function(e){e?(a.ba=!0,J5(a.F,d),M5(a,d),a.U="unknown",P5(a,c)):(g.Co(Error("CastSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online.")),a.hg())},5)},LIa=function(a,b){g.Ho(a.W);
a.W=0;b?a.ea.d4&&b.loungeToken?b.deviceId?a.getScreen()&&a.getScreen().uuid==b.deviceId||(b.loungeTokenRefreshIntervalMs?QIa(a,{name:a.u.friendlyName,screenId:b.screenId,loungeToken:b.loungeToken,dialId:b.deviceId,screenIdType:"shortLived"},b.loungeTokenRefreshIntervalMs):(g.Co(Error("No loungeTokenRefreshIntervalMs presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),Q5(a,b.screenId))):(g.Co(Error("No device id presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),Q5(a,b.screenId)):
Q5(a,b.screenId):a.hg(Error("Waiting for session status timed out."))},OIa=function(a,b){g.Ho(a.D);
a.D=0;var c=null;if(b)if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";else c="noLoungeTokenResponse";c?(a.info("Did not receive a new lounge token in onLoungeToken_ with data: "+(JSON.stringify(b)+", error: "+c)),a.U=c,P5(a,3E4)):(a.C&&(a.C.token=b.loungeToken,J5(a.F,a.C)),a.V("sessionScreen",a.C),a.ba=!1,a.U="unknown",P5(a,b.loungeTokenRefreshIntervalMs))},PIa=function(a,b,c,d){g.Ho(a.I);
a.I=0;IIa(a.F,b,function(e){e||0>d?c(e):a.I=g.Fo(function(){PIa(a,b,c,d-1)},300)})},RIa=function(a){g.Ho(a.L);
a.L=0;g.Ho(a.I);a.I=0;g.Ho(a.W);a.W=0;g.Ho(a.D);a.D=0;g.Ho(a.K);a.K=0},R5=function(a,b,c){L5.call(this,a,b,"DialSession");
this.D=this.L=null;this.U="";this.ba=c;this.W=null;this.K=g.Ka;this.I=NaN;this.X=(0,g.z)(this.aL,this);this.B=g.Ka},SIa=function(a){a.B=a.F.cI(a.U,a.u.label,a.u.friendlyName,(0,g.z)(function(b){this.B=g.Ka;
M5(this,b)},a),(0,g.z)(function(b){this.B=g.Ka;
this.hg(b)},a))},TIa=function(a){var b={};
b.pairingCode=a.U;b.theme=a.ba;uHa()&&(b.env_useStageMdx=1);return g.Jd(b)},S5=function(a,b){L5.call(this,a,b,"ManualSession");
this.B=g.Fo((0,g.z)(this.kp,this,null),150)},T5=function(a,b){g.N.call(this);
this.D=b;this.B=a;this.L=b.appId||"233637DE";this.K=b.theme||"cl";this.U=b.disableCastApi||!1;this.u=null;this.I=!1;this.C=[];this.F=(0,g.z)(this.lP,this)},UIa=function(a,b){return b?g.eb(a.C,function(c){return r4(b,c.label)},a):null},U5=function(a){u5("Controller",a)},rIa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},V5=function(a){return a.I||!!a.C.length||!!a.u},W5=function(a,b,c){b!=a.u&&(g.ag(a.u),(a.u=b)?(c?a.V("yt-remote-cast2-receiver-resumed",
b.u):a.V("yt-remote-cast2-receiver-selected",b.u),b.subscribe("sessionScreen",(0,g.z)(a.hG,a,b)),b.getScreen()?a.V("yt-remote-cast2-session-change",b.getScreen()):c&&a.u.kp(null)):a.V("yt-remote-cast2-session-change",null))},VIa=function(a){var b=a.B.bI(),c=a.u&&a.u.u;
a=g.Oc(b,function(d){c&&r4(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=UIa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},aJa=function(a,b,c,d){d.disableCastApi?X5("Cannot initialize because disabled by Mdx config."):WIa()?XIa(b,d)&&(Y5(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?YIa(a,c):(window.__onGCastApiAvailable=function(e,f){e?YIa(a,c):(Z5("Failed to load cast API: "+f),$5(!1),Y5(!1),g.wu("yt-remote-cast-available"),g.wu("yt-remote-cast-receiver"),
ZIa(),c(!1))},d.loadCastApiSetupScript?g.Ro("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?BHa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?E4():(AHa(),D4($Ia.map(yHa))))):X5("Cannot initialize because not running Chrome")},ZIa=function(){X5("dispose");
var a=a6();a&&a.dispose();g.Fa("yt.mdx.remote.cloudview.instance_",null,void 0);bJa(!1);g.No(b6);b6.length=0},c6=function(){return!!g.vu("yt-remote-cast-installed")},cJa=function(){var a=g.vu("yt-remote-cast-receiver");
return a?a.friendlyName:null},dJa=function(){X5("clearCurrentReceiver");
g.wu("yt-remote-cast-receiver")},eJa=function(){return c6()?a6()?a6().getCastSession():(Z5("getCastSelector: Cast is not initialized."),null):(Z5("getCastSelector: Cast API is not installed!"),null)},e6=function(){c6()?a6()?d6()?(X5("Requesting cast selector."),a6().requestSession()):(X5("Wait for cast API to be ready to request the session."),b6.push(g.Mo("yt-remote-cast2-api-ready",e6))):Z5("requestCastSelector: Cast is not initialized."):Z5("requestCastSelector: Cast API is not installed!")},f6=
function(a,b){d6()?a6().setConnectedScreenStatus(a,b):Z5("setConnectedScreenStatus called before ready.")},WIa=function(){var a=0<=g.Vc.search(/ (CrMo|Chrome|CriOS)\//);
return g.lB||a},fJa=function(a,b){a6().init(a,b)},XIa=function(a,b){var c=!1;
a6()||(c=new T5(a,b),c.subscribe("yt-remote-cast2-availability-change",function(d){g.uu("yt-remote-cast-available",d);o4("yt-remote-cast2-availability-change",d)}),c.subscribe("yt-remote-cast2-receiver-selected",function(d){X5("onReceiverSelected: "+d.friendlyName);
g.uu("yt-remote-cast-receiver",d);o4("yt-remote-cast2-receiver-selected",d)}),c.subscribe("yt-remote-cast2-receiver-resumed",function(d){X5("onReceiverResumed: "+d.friendlyName);
g.uu("yt-remote-cast-receiver",d);o4("yt-remote-cast2-receiver-resumed",d)}),c.subscribe("yt-remote-cast2-session-change",function(d){X5("onSessionChange: "+s4(d));
d||g.wu("yt-remote-cast-receiver");o4("yt-remote-cast2-session-change",d)}),g.Fa("yt.mdx.remote.cloudview.instance_",c,void 0),c=!0);
X5("cloudview.createSingleton_: "+c);return c},a6=function(){return g.Ja("yt.mdx.remote.cloudview.instance_")},YIa=function(a,b){$5(!0);
Y5(!1);fJa(a,function(c){c?(bJa(!0),g.Oo("yt-remote-cast2-api-ready")):(Z5("Failed to initialize cast API."),$5(!1),g.wu("yt-remote-cast-available"),g.wu("yt-remote-cast-receiver"),ZIa());b(c)})},X5=function(a){u5("cloudview",a)},Z5=function(a){u5("cloudview",a)},$5=function(a){X5("setCastInstalled_ "+a);
g.uu("yt-remote-cast-installed",a)},d6=function(){return!!g.Ja("yt.mdx.remote.cloudview.apiReady_")},bJa=function(a){X5("setApiReady_ "+a);
g.Fa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},Y5=function(a){g.Fa("yt.mdx.remote.cloudview.initializing_",a,void 0)},g6=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.K=this.L=0;this.u=null;this.hasNext=this.rj=!1;this.U=this.I=this.B=this.F=0;this.D=NaN;this.C=!1;this.reset(a)},h6=function(a){a.audioTrackId=null;
a.u=null;a.playerState=-1;a.rj=!1;a.hasNext=!1;a.L=0;a.K=g.A();a.F=0;a.B=0;a.I=0;a.U=0;a.D=NaN;a.C=!1},i6=function(a){return a.Hb()?(g.A()-a.K)/1E3:0},j6=function(a,b){a.L=b;
a.K=g.A()},k6=function(a){switch(a.playerState){case 1:case 1081:return(g.A()-a.K)/1E3+a.L;
case -1E3:return 0}return a.L},l6=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&h6(a)},m6=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Wb(a.u);b.hasPrevious=a.rj;b.hasNext=a.hasNext;b.playerTime=a.L;b.playerTimeAt=a.K;b.seekableStart=a.F;b.seekableEnd=a.B;b.duration=a.I;b.loadedTime=a.U;b.liveIngestionTime=a.D;return b},o6=function(a,b){g.N.call(this);
this.Ja=0;this.C=a;this.F=[];this.D=new nIa;this.B=this.u=null;this.L=(0,g.z)(this.NN,this);this.I=(0,g.z)(this.Xr,this);this.K=(0,g.z)(this.MN,this);this.U=(0,g.z)(this.UN,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.oA,this),gJa(this))):c=3;0!=c&&(b?this.oA(c):g.Fo((0,g.z)(function(){this.oA(c)},this),0));
var d=eJa();d&&n6(this,d);this.subscribe("yt-remote-cast2-session-change",this.U)},p6=function(a){return new g6(a.C.getPlayerContextData())},gJa=function(a){g.Cb("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.F.push(this.C.subscribe(b,g.Sa(this.iP,b),this))},a)},hJa=function(a){g.Cb(a.F,function(b){this.C.unsubscribeByKey(b)},a);
a.F.length=0},q6=function(a){return 1==a.getState()},r6=function(a,b){var c=a.D;
50>c.u.length+c.B.length&&a.D.B.push(b)},t6=function(a,b,c){var d=p6(a);
j6(d,c);-1E3!=d.playerState&&(d.playerState=b);s6(a,d)},u6=function(a,b,c){a.C.sendMessage(b,c)},s6=function(a,b){hJa(a);
a.C.setPlayerContextData(m6(b));gJa(a)},n6=function(a,b){a.B&&(a.B.removeUpdateListener(a.L),a.B.removeMediaListener(a.I),a.Xr(null));
a.B=b;a.B&&(u5("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.L),a.B.addMediaListener(a.I),a.B.media.length&&a.Xr(a.B.media[0]))},iJa=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=p6(a);b.contentId!=d.videoId&&u5("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;j6(d,a.u.getEstimatedTime());s6(a,d)}else u5("CP","No cast media video. Ignoring state update.")},v6=function(a,b,c){return(0,g.z)(function(d){this.Ed("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Ed("Retrying "+b+" using MDx browser channel."),u6(this,b,c))},a)},w6=function(a,b,c){g.N.call(this);
this.F=NaN;this.X=!1;this.L=this.K=this.U=this.W=NaN;this.ba=[];this.D=this.I=this.C=this.Jb=this.u=null;this.ea=a;this.ba.push(g.gp(window,"beforeunload",(0,g.z)(this.XJ,this)));this.B=[];this.Jb=new g6;this.ga=b.id;this.da=b.idType;this.u=jJa(this,c);this.u.subscribe("handlerOpened",this.RN,this);this.u.subscribe("handlerClosed",this.ON,this);this.u.subscribe("handlerError",this.PN,this);this.u.subscribe("handlerMessage",this.QN,this);this.u.Ev(b.token);this.subscribe("remoteQueueChange",function(){var d=
this.Jb.videoId;g.xu()&&g.uu("yt-remote-session-video-id",d)},this)},x6=function(a){u5("conn",a)},jJa=function(a,b){return new n5(r5(a.ea,"/bc"),b,!1,function(){return a.ZH()},"shortLived"==a.da)},y6=function(a,b){a.V("proxyStateChange",b)},kJa=function(a){a.F=g.Fo((0,g.z)(function(){x6("Connecting timeout");
this.Ho(1)},a),2E4)},z6=function(a){g.Ho(a.F);
a.F=NaN},A6=function(a){g.Ho(a.W);
a.W=NaN},lJa=function(a){B6(a);
a.U=g.Fo((0,g.z)(function(){C6(this,"getNowPlaying")},a),2E4)},B6=function(a){g.Ho(a.U);
a.U=NaN},nJa=function(a,b){b&&(z6(a),A6(a));
var c=p5(a.u)&&isNaN(a.F);b==c?b&&(y6(a,1),C6(a,"getSubtitlesTrack")):b?(a.iD()&&a.Jb.reset(),y6(a,1),C6(a,"getNowPlaying"),mJa(a)):a.Ho(1)},oJa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Jb.videoId&&(g.Rb(b.params)?a.Jb.u=null:a.Jb.u=b.params,a.V("remotePlayerChange"))},pJa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Jb.listId=b.params.listId||a.Jb.listId;l6(a.Jb,c,d);a.V("remoteQueueChange")},rJa=function(a,b){b.params=b.params||{};
pJa(a,b);qJa(a,b);a.V("autoplayDismissed")},qJa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
j6(a.Jb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Jb.playerState&&(c=-1E3);a.Jb.playerState=c;c=Number(b.params.loadedTime);a.Jb.U=isNaN(c)?0:c;c=Number(b.params.duration);a.Jb.I=isNaN(c)?0:c;c=a.Jb;var d=Number(b.params.liveIngestionTime);c.D=d;c.C=isNaN(d)?!1:!0;c=a.Jb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.F=isNaN(d)?0:d;c.B=isNaN(e)?0:e;1==a.Jb.playerState?lJa(a):B6(a);a.V("remotePlayerChange")},sJa=function(a,b){if(-1E3!=
a.Jb.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Jb.playerState=c;c=parseInt(b.params.currentTime,10);j6(a.Jb,isNaN(c)?0:c);a.V("remotePlayerChange")}},tJa=function(a,b){var c="true"==b.params.muted;
a.Jb.volume=parseInt(b.params.volume,10);a.Jb.muted=c;a.V("remotePlayerChange")},uJa=function(a,b){a.I=b.params.videoId;
a.V("nowAutoplaying",parseInt(b.params.timeout,10))},vJa=function(a,b){var c="true"==b.params.hasNext;
a.Jb.rj="true"==b.params.hasPrevious;a.Jb.hasNext=c;a.V("previousNextChange")},mJa=function(a){g.Ho(a.L);
a.L=g.Fo((0,g.z)(a.Ho,a,1),864E5)},C6=function(a,b,c){c?x6("Sending: action="+b+", params="+g.Qj(c)):x6("Sending: action="+b);
a.u.sendMessage(b,c)},D6=function(a){y5.call(this,"ScreenServiceProxy");
this.Jf=a;this.u=[];this.u.push(this.Jf.$_s("screenChange",(0,g.z)(this.ZK,this)));this.u.push(this.Jf.$_s("onlineScreenChange",(0,g.z)(this.PO,this)))},zJa=function(a,b){tHa();
if(!C4||!C4.get("yt-remote-disable-remote-module-for-dev")){b=g.L("MDX_CONFIG")||b;lHa();A4();E6||(E6=new q5(b?b.loungeApiHost:void 0),uHa()&&(E6.u="/api/loungedev"));F6||(F6=g.Ja("yt.mdx.remote.deferredProxies_")||[],g.Fa("yt.mdx.remote.deferredProxies_",F6,void 0));wJa();var c=G6();if(!c){var d=new I5(E6);g.Fa("yt.mdx.remote.screenService_",d,void 0);c=G6();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,disableCastApi:b.disableCastApi,
enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken});aJa(a,d,function(h){h?H6()&&f6(H6(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){o4("yt-remote-receiver-availability-change")})},e)}if(b&&!g.Ja("yt.mdx.remote.initialized_")){g.Fa("yt.mdx.remote.initialized_",!0,void 0);
I6("Initializing: "+g.Qj(b));J6.push(g.Mo("yt-remote-cast2-availability-change",function(){o4("yt-remote-receiver-availability-change")}));
J6.push(g.Mo("yt-remote-cast2-receiver-selected",function(){K6(null);o4("yt-remote-auto-connect","cast-selector-receiver")}));
J6.push(g.Mo("yt-remote-cast2-receiver-resumed",function(){o4("yt-remote-receiver-resumed","cast-selector-receiver")}));
J6.push(g.Mo("yt-remote-cast2-session-change",xJa));J6.push(g.Mo("yt-remote-connection-change",function(h){h?f6(H6(),"YouTube TV"):L6()||(f6(null,null),dJa())}));
e=M6();b.isAuto&&(e.id+="#dial");g.Vo("desktop_enable_autoplay")&&(e.capabilities=["atp"]);e.name=b.device;e.app=b.app;var f=b.theme;f&&(e.theme=f);I6(" -- with channel params: "+g.Qj(e));e?(g.uu("yt-remote-session-app",e.app),g.uu("yt-remote-session-name",e.name)):(g.wu("yt-remote-session-app"),g.wu("yt-remote-session-name"));g.Fa("yt.mdx.remote.channelParams_",e,void 0);c.start();H6()||yJa()}}},AJa=function(){var a=G6().Jf.$_gos();
var b=N6();b&&O6()&&(v4(a,b)||a.push(b));return kHa(a)},P6=function(){var a=BJa();
!a&&c6()&&cJa()&&(a={key:"cast-selector-receiver",name:cJa()});return a},BJa=function(){var a=AJa(),b=N6();
b||(b=L6());return g.eb(a,function(c){return b&&r4(b,c.key)?!0:!1})},N6=function(){var a=H6();
if(!a)return null;var b=G6().Sg();return w4(b,a)},xJa=function(a){I6("remote.onCastSessionChange_: "+s4(a));
if(a){var b=N6();if(b&&b.id==a.id){if(f6(b.id,"YouTube TV"),"shortLived"==a.idType&&(a=a.token))Q6&&(Q6.token=a),(b=O6())&&b.Ev(a)}else b&&R6(),S6(a,1)}else O6()&&R6()},R6=function(){d6()?a6().stopSession():Z5("stopSession called before API ready.");
var a=O6();a&&(a.disconnect(1),T6(null))},U6=function(){var a=O6();
return!!a&&3!=a.getProxyState()},I6=function(a){u5("remote",a)},G6=function(){if(!V6){var a=g.Ja("yt.mdx.remote.screenService_");
V6=a?new D6(a):null}return V6},H6=function(){return g.Ja("yt.mdx.remote.currentScreenId_")},CJa=function(a){g.Fa("yt.mdx.remote.currentScreenId_",a,void 0)},DJa=function(){return g.Ja("yt.mdx.remote.connectData_")},K6=function(a){g.Fa("yt.mdx.remote.connectData_",a,void 0)},O6=function(){return g.Ja("yt.mdx.remote.connection_")},T6=function(a){var b=O6();
K6(null);a||CJa("");g.Fa("yt.mdx.remote.connection_",a,void 0);F6&&(g.Cb(F6,function(c){c(a)}),F6.length=0);
b&&!a?o4("yt-remote-connection-change",!1):!b&&a&&o4("yt-remote-connection-change",!0)},L6=function(){var a=g.xu();
if(!a)return null;var b=G6();if(!b)return null;b=b.Sg();return w4(b,a)},S6=function(a,b){H6();
N6()&&N6();if(W6)Q6=a;else{CJa(a.id);var c=new w6(E6,a,M6());c.connect(b,DJa());c.subscribe("beforeDisconnect",function(d){o4("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){O6()&&(O6(),T6(null))});
c.subscribe("browserChannelAuthError",function(){var d=N6();d&&"shortLived"==d.idType&&(d6()?a6().handleBrowserChannelAuthError():Z5("refreshLoungeToken called before API ready."))});
T6(c)}},yJa=function(){var a=L6();
a?(I6("Resume connection to: "+s4(a)),S6(a,0)):(B4(),dJa(),I6("Skipping connecting because no session screen found."))},wJa=function(){var a=M6();
if(g.Rb(a)){a=z4();var b=g.vu("yt-remote-session-name")||"",c=g.vu("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Fa("yt.mdx.remote.channelParams_",a,void 0)}},M6=function(){return g.Ja("yt.mdx.remote.channelParams_")||{}},X6=function(a,b,c){g.B.call(this);
var d=this;this.B=a;this.J=b;this.ub=c;this.events=new g.dO(this);this.W=this.events.P(this.J,"onVolumeChange",function(e){EJa(d,e)});
this.F=!1;this.suggestion=null;this.I=new g.VK(64);this.u=new g.F(this.nH,500,this);this.C=new g.F(this.oH,1E3,this);this.L=new F4(this.HR,0,this);this.D={};this.U=new g.F(this.PH,1E3,this);this.K=new G4(this.seekTo,1E3,this);this.X=g.Ka;g.C(this,this.events);this.events.P(b,"onCaptionsTrackListChanged",this.yO);this.events.P(b,"captionschanged",this.KN);this.events.P(b,"captionssettingschanged",this.rH);this.events.P(b,"videoplayerreset",this.gv);this.events.P(b,"mdxautoplaycancel",function(){d.ub.zC()});
a=this.ub;a.ma();a.subscribe("proxyStateChange",this.cG,this);a.subscribe("remotePlayerChange",this.ks,this);a.subscribe("remoteQueueChange",this.gv,this);a.subscribe("previousNextChange",this.ZF,this);a.subscribe("nowAutoplaying",this.UF,this);a.subscribe("autoplayDismissed",this.sF,this);g.C(this,this.u);g.C(this,this.C);g.C(this,this.L);g.C(this,this.U);g.C(this,this.K);this.rH();this.gv();this.ks()},EJa=function(a,b){if(Y6(a)){a.ub.unsubscribe("remotePlayerChange",a.ks,a);
var c=Math.round(b.volume),d=!!b.muted,e=p6(a.ub);if(c!==e.volume||d!==e.muted)a.ub.setVolume(c,d),a.U.start();a.ub.subscribe("remotePlayerChange",a.ks,a)}},FJa=function(a){a.Cb(0);
a.u.stop();a.sb(new g.VK(64))},Z6=function(a,b){if(Y6(a)&&!a.F){var c=null;
b&&(c={style:a.J.getSubtitlesUserSettings()},g.Yb(c,b));a.ub.aI(a.J.getVideoData(1).videoId,c);a.D=p6(a.ub).u}},$6=function(a,b){var c=a.J.getPlaylist();
if(null===c||void 0===c?0:c.listId){var d=c.index;var e=c.listId.toString()}c=a.J.getVideoData(1);a.ub.playVideo(c.videoId,b,d,e,c.playerParams,c.ea,YGa(c));a.sb(new g.VK(1))},GJa=function(a,b){if(b){var c=a.J.getOption("captions","tracklist",{ID:1});
c&&c.length?(a.J.setOption("captions","track",b),a.F=!1):(a.J.loadModule("captions"),a.F=!0)}else a.J.setOption("captions","track",{})},Y6=function(a){return p6(a.ub).videoId===a.J.getVideoData(1).videoId},a7=function(){g.U.call(this,{G:"div",
N:"ytp-mdx-manual-pairing-popup-dialog",T:{role:"dialog"},R:[{G:"div",N:"ytp-mdx-manual-pairing-popup-dialog-inner-content",R:[{G:"div",N:"ytp-mdx-manual-pairing-popup-title",aa:"Connecting to your TV on web using a code will be going away soon"},{G:"div",N:"ytp-mdx-manual-pairing-popup-buttons",R:[{G:"button",ia:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],aa:"Learn more"},{G:"button",ia:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],aa:"OK"}]}]}]});this.u=new g.zM(this,250);this.learnMoreButton=
this.ha("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.ha("ytp-mdx-manual-pairing-popup-ok");g.C(this,this.u);this.P(this.learnMoreButton,"click",this.B);this.P(this.okButton,"click",this.C)},b7=function(){g.U.call(this,{G:"div",
N:"ytp-mdx-popup-dialog",T:{role:"dialog"},R:[{G:"div",N:"ytp-mdx-popup-dialog-inner-content",R:[{G:"div",N:"ytp-mdx-popup-title",aa:"You're signed out"},{G:"div",N:"ytp-mdx-popup-description",aa:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{G:"div",N:"ytp-mdx-privacy-popup-buttons",R:[{G:"button",ia:["ytp-button","ytp-mdx-privacy-popup-cancel"],aa:"Cancel"},{G:"button",ia:["ytp-button",
"ytp-mdx-privacy-popup-confirm"],aa:"Confirm"}]}]}]});this.u=new g.zM(this,250);this.cancelButton=this.ha("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.ha("ytp-mdx-privacy-popup-confirm");g.C(this,this.u);this.P(this.cancelButton,"click",this.B);this.P(this.confirmButton,"click",this.C)},c7=function(a){g.U.call(this,{G:"div",
N:"ytp-remote",R:[{G:"div",N:"ytp-remote-display-status",R:[{G:"div",N:"ytp-remote-display-status-icon",R:[g.kna()]},{G:"div",N:"ytp-remote-display-status-text",aa:"{{statustext}}"}]}]});this.api=a;this.u=new g.zM(this,250);g.C(this,this.u);this.P(a,"presentingplayerstatechange",this.B);HJa(this,a.Ua())},HJa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.T(b,128)?g.qK("Error on $RECEIVER_NAME",c):b.Hb()||g.T(b,4)?g.qK("Playing on $RECEIVER_NAME",c):g.qK("Connected to $RECEIVER_NAME",c);a.ya("statustext",c);a.u.show()}else a.u.hide()},d7=function(a,b){g.AR.call(this,"Play on",0,a,b);
this.J=a;this.fm={};this.P(a,"onMdxReceiversChange",this.D);this.P(a,"presentingplayerstatechange",this.D);this.D()},e7=function(a){g.nO.call(this,a);
this.ii={key:u4(),name:"This computer"};this.mh=null;this.subscriptions=[];this.Oz=this.ub=null;this.fm=[this.ii];this.nl=this.ii;this.Nc=new g.VK(64);this.bE=0;this.Ne=-1;this.pp=null;this.qs=this.yu=!1;this.Gn=this.Np=null;if(!g.RD(this.player.S())){a=this.player;var b=g.SN(a);b&&(b=b.Bl())&&(b=new d7(a,b),g.C(this,b));b=new c7(a);g.C(this,b);g.bO(a,b.element,4);this.Np=new b7;g.C(this,this.Np);g.bO(a,this.Np.element,4);g.P(this.player.S().experiments,"pair_servlet_deprecation_warning_enabled")&&
!g.P(this.player.S().experiments,"deprecate_pair_servlet_enabled")&&(this.pp=new a7,g.C(this,this.pp),g.bO(a,this.pp.element,4));this.qs=!!L6();this.yu=!!g.vu("yt-remote-manual-pairing-warning-shown")}},f7=function(a){a.Gn&&(a.player.removeEventListener("presentingplayerstatechange",a.Gn),a.Gn=null)},IJa=function(a,b,c){a.Nc=c;
a.player.V("presentingplayerstatechange",new g.QJ(c,b))},JJa=function(a,b,c){var d=!1;
1===b?d=!a.qs:2===b&&(d=!a.yu);d&&g.SJ(c,8)&&(a.player.pauseVideo(),f7(a))},g7=function(a,b){if(b.key!==a.nl.key)if(b.key===a.ii.key)R6();
else{if(a.pp&&!a.yu&&b!==a.ii&&"cast-selector-receiver"!==b.key&&g.bE(a.player.S()))KJa(a);else{var c;(c=!g.P(a.player.S().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.L("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.L("SESSION_INDEX")&&!g.L("LOGGED_IN")))||a.qs||!a.Np);(c?0:g.bE(a.player.S())||g.vE(a.player.S()))&&LJa(a)}a.nl=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.P(a.player.S().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.length;l++)h[l]=f.La(l).videoId}else h=[e];f=a.player.getCurrentTime(1);d={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.ea,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=YGa(c))&&(d.locationInfo=c);c=d}I6("Connecting to: "+g.Qj(b));"cast-selector-receiver"==b.key?(K6(c||null),c=c||null,
d6()?a6().setLaunchParams(c):Z5("setLaunchParams called before ready.")):!c&&U6()&&H6()==b.key?o4("yt-remote-connection-change",!0):(R6(),K6(c||null),c=G6().Sg(),(c=w4(c,b.key))&&S6(c,1))}},LJa=function(a){a.player.Ua().Hb()?a.player.pauseVideo():(a.Gn=function(b){JJa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.Gn));
a.Np&&a.Np.Dc();O6()||(W6=!0)},KJa=function(a){a.player.Ua().Hb()?a.player.pauseVideo():(a.Gn=function(b){JJa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.Gn));
a.pp&&a.pp.Dc();O6()||(W6=!0)},LHa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},V4={"'":"\\'"},MJa={},gHa={MS:"atp",U1:"ska",S0:"que",b_:"mus",T1:"sus",vW:"dsp",m1:"seq",GZ:"mic",vV:"dpa"},C4,y4="",zHa=vHa("loadCastFramework")||vHa("loadCastApplicationFramework"),$Ia=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ua(F4,g.B);g.k=F4.prototype;g.k.UJ=function(a){this.D=arguments;this.u=!1;this.fb?this.C=g.A()+this.Kf:this.fb=g.Mm(this.F,this.Kf)};
g.k.stop=function(){this.fb&&(g.v.clearTimeout(this.fb),this.fb=null);this.C=null;this.u=!1;this.D=[]};
g.k.pause=function(){++this.B};
g.k.resume=function(){this.B&&(--this.B,!this.B&&this.u&&(this.u=!1,this.I.apply(null,this.D)))};
g.k.ca=function(){this.stop();F4.Od.ca.call(this)};
g.k.VJ=function(){this.C?(this.fb=g.Mm(this.F,this.C-g.A()),this.C=null):(this.fb=null,this.B?this.u=!0:(this.u=!1,this.I.apply(null,this.D)))};g.u(G4,g.B);g.k=G4.prototype;g.k.tE=function(a){this.C=arguments;this.fb||this.B?this.u=!0:H4(this)};
g.k.stop=function(){this.fb&&(g.v.clearTimeout(this.fb),this.fb=null,this.u=!1,this.C=null)};
g.k.pause=function(){this.B++};
g.k.resume=function(){this.B--;this.B||!this.u||this.fb||(this.u=!1,H4(this))};
g.k.ca=function(){g.B.prototype.ca.call(this);this.stop()};J4.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
J4.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};var L4=new g.bm;g.u(CHa,g.Fl);N4.prototype.u=null;N4.prototype.getOptions=function(){var a;(a=this.u)||(a={},EHa(this)&&(a[0]=!0,a[1]=!0),a=this.u=a);return a};var h7;g.Ua(DHa,N4);h7=new DHa;g.k=O4.prototype;g.k.nn=null;g.k.Ei=!1;g.k.fq=null;g.k.YA=null;g.k.Qp=null;g.k.Yp=null;g.k.dl=null;g.k.hm=null;g.k.Hn=null;g.k.Be=null;g.k.Zs=0;g.k.Ii=null;g.k.ew=null;g.k.El=null;g.k.qr=-1;g.k.cH=!0;g.k.Vm=!1;g.k.oy=0;g.k.tv=null;var JHa={},R4={};g.k=O4.prototype;g.k.setTimeout=function(a){this.F=a};
g.k.IQ=function(a){a=a.target;var b=this.tv;b&&3==$4(a)?b.tE():this.XH(a)};
g.k.XH=function(a){try{if(a==this.Be)a:{var b=$4(this.Be),c=this.Be.I,d=this.Be.getStatus();if(g.ze&&!g.ae(10)||g.Be&&!g.$d("420+")){if(4>b)break a}else if(3>b||3==b&&!g.ug&&!b5(this.Be))break a;this.Vm||4!=b||7==c||(8==c||0>=d?this.u.ni(3):this.u.ni(2));W4(this);var e=this.Be.getStatus();this.qr=e;var f=b5(this.Be);(this.Ei=200==e)?(4==b&&T4(this),this.I?(KHa(this,b,f),g.ug&&this.Ei&&3==b&&(this.D.va(this.C,"tick",this.BQ),this.C.start())):S4(this,f),this.Ei&&!this.Vm&&(4==b?this.u.cu(this):(this.Ei=
!1,Q4(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.El=3,M4(13)):(this.El=0,M4(14)),T4(this),U4(this))}}catch(h){this.Be&&b5(this.Be)}finally{}};
g.k.BQ=function(){var a=$4(this.Be),b=b5(this.Be);this.Zs<b.length&&(W4(this),KHa(this,a,b),this.Ei&&4!=a&&Q4(this))};
g.k.bQ=function(a){K4((0,g.z)(this.aQ,this,a),0)};
g.k.aQ=function(a){this.Vm||(W4(this),S4(this,a),Q4(this))};
g.k.lG=function(a){K4((0,g.z)(this.ZP,this,a),0)};
g.k.ZP=function(a){this.Vm||(T4(this),this.Ei=a,this.u.cu(this),this.u.ni(4))};
g.k.cancel=function(){this.Vm=!0;T4(this)};
g.k.iQ=function(){this.fq=null;var a=g.A();0<=a-this.YA?(2!=this.Yp&&this.u.ni(3),T4(this),this.El=2,M4(18),U4(this)):NHa(this,this.YA-a)};
g.k.getLastError=function(){return this.El};g.Ua(Y4,g.bm);var UHa=/^https?$/i,NJa=["POST","PUT"];g.k=Y4.prototype;
g.k.send=function(a,b,c,d){if(this.u)throw Error("[goog.net.XhrIo] Object is active with another request="+this.U+"; newUri="+a);b=b?b.toUpperCase():"GET";this.U=a;this.D="";this.I=0;this.xa=b;this.ga=!1;this.C=!0;this.u=this.da?FHa(this.da):FHa(h7);this.ba=this.da?this.da.getOptions():h7.getOptions();this.u.onreadystatechange=(0,g.z)(this.aG,this);try{n4(a5(this,"Opening Xhr")),this.ka=!0,this.u.open(b,String(a),!0),this.ka=!1}catch(f){n4(a5(this,"Error opening Xhr: "+f.message));THa(this,f);return}a=
c||"";var e=this.headers.clone();d&&cHa(d,function(f,h){e.set(h,f)});
d=g.eb(e.sh(),RHa);c=g.v.FormData&&a instanceof g.v.FormData;!g.ib(NJa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.u.setRequestHeader(h,f)},this);
this.za&&(this.u.responseType=this.za);"withCredentials"in this.u&&this.u.withCredentials!==this.ea&&(this.u.withCredentials=this.ea);try{WHa(this),0<this.K&&(this.X=QHa(this.u),n4(a5(this,"Will abort after "+this.K+"ms if incomplete, xhr2 "+this.X)),this.X?(this.u.timeout=this.K,this.u.ontimeout=(0,g.z)(this.rD,this)):this.W=g.Mm(this.rD,this.K,this)),n4(a5(this,"Sending request")),this.L=!0,this.u.send(a),this.L=!1}catch(f){n4(a5(this,"Send error: "+f.message)),THa(this,f)}};
g.k.rD=function(){"undefined"!=typeof g.u_&&this.u&&(this.D="Timed out after "+this.K+"ms, aborting",this.I=8,a5(this,this.D),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.u&&this.C&&(a5(this,"Aborting"),this.C=!1,this.F=!0,this.u.abort(),this.F=!1,this.I=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Z4(this))};
g.k.ca=function(){this.u&&(this.C&&(this.C=!1,this.F=!0,this.u.abort(),this.F=!1),Z4(this,!0));Y4.Od.ca.call(this)};
g.k.aG=function(){this.ma()||(this.ka||this.L||this.F?VHa(this):this.kP())};
g.k.kP=function(){VHa(this)};
g.k.isActive=function(){return!!this.u};
g.k.isComplete=function(){return 4==$4(this)};
g.k.getStatus=function(){try{return 2<$4(this)?this.u.status:-1}catch(a){return-1}};
g.k.getResponseHeader=function(a){if(this.u&&this.isComplete())return a=this.u.getResponseHeader(a),null===a?void 0:a};
g.k.getLastError=function(){return"string"===typeof this.D?this.D:String(this.D)};g.k=XHa.prototype;g.k.my=null;g.k.Gg=null;g.k.vv=!1;g.k.qD=null;g.k.Dt=null;g.k.Uy=null;g.k.ny=null;g.k.Ja=null;g.k.tk=-1;g.k.mr=null;g.k.tq=null;g.k.connect=function(a){this.ny=a;a=c5(this.u,null,this.ny);M4(3);this.qD=g.A();var b=this.u.K;null!=b?(this.mr=b[0],(this.tq=b[1])?(this.Ja=1,YHa(this)):(this.Ja=2,e5(this))):(l4(a,"MODE","init"),this.Gg=new O4(this,void 0,void 0,void 0),this.Gg.nn=this.my,P4(this.Gg,a,!1,null,!0),this.Ja=0)};
g.k.XI=function(a){if(a)this.Ja=2,e5(this);else{M4(4);var b=this.u;b.pj=b.kl.tk;l5(b,9)}a&&this.ni(2)};
g.k.yx=function(a){return this.u.yx(a)};
g.k.abort=function(){this.Gg&&(this.Gg.cancel(),this.Gg=null);this.tk=-1};
g.k.pD=function(){return!1};
g.k.dG=function(a,b){this.tk=a.qr;if(0==this.Ja)if(b){try{var c=this.B.parse(b)}catch(d){c=this.u;c.pj=this.tk;l5(c,2);return}this.mr=c[0];this.tq=c[1]}else c=this.u,c.pj=this.tk,l5(c,2);else if(2==this.Ja)if(this.vv)M4(7),this.Uy=g.A();else if("11111"==b){if(M4(6),this.vv=!0,this.Dt=g.A(),c=this.Dt-this.qD,!g.ze||g.ae(10)||500>c)this.tk=200,this.Gg.cancel(),M4(12),d5(this.u,this,!0)}else M4(8),this.Dt=this.Uy=g.A(),this.vv=!1};
g.k.cu=function(){this.tk=this.Gg.qr;if(this.Gg.Ei)0==this.Ja?this.tq?(this.Ja=1,YHa(this)):(this.Ja=2,e5(this)):2==this.Ja&&((!g.ze||g.ae(10)?!this.vv:200>this.Uy-this.Dt)?(M4(11),d5(this.u,this,!1)):(M4(12),d5(this.u,this,!0)));else{0==this.Ja?M4(9):2==this.Ja&&M4(10);var a=this.u;this.Gg.getLastError();a.pj=this.tk;l5(a,2)}};
g.k.Hs=function(){return this.u.Hs()};
g.k.isActive=function(){return this.u.isActive()};
g.k.ni=function(a){this.u.ni(a)};g.k=f5.prototype;g.k.oj=null;g.k.Nq=null;g.k.sg=null;g.k.ae=null;g.k.ly=null;g.k.Et=null;g.k.TB=null;g.k.au=null;g.k.Vr=0;g.k.bN=0;g.k.If=null;g.k.sl=null;g.k.ak=null;g.k.cn=null;g.k.kl=null;g.k.bw=null;g.k.jp=-1;g.k.aE=-1;g.k.pj=-1;g.k.Lo=0;g.k.vo=0;g.k.Wm=8;g.Ua($Ha,g.Fl);g.Ua(aIa,g.Fl);g.k=f5.prototype;g.k.connect=function(a,b,c,d,e){M4(0);this.ly=b;this.Nq=c||{};d&&void 0!==e&&(this.Nq.OSID=d,this.Nq.OAID=e);this.F?(K4((0,g.z)(this.lC,this,a),100),eIa(this)):this.lC(a)};
g.k.lC=function(a){this.kl=new XHa(this);this.kl.my=this.oj;this.kl.B=this.D;this.kl.connect(a)};
g.k.pD=function(){return 0==this.Ja};
g.k.getState=function(){return this.Ja};
g.k.kG=function(a){this.sl=null;iIa(this,a)};
g.k.jG=function(){this.ak=null;this.ae=new O4(this,this.B,"rpc",this.I);this.ae.nn=this.oj;this.ae.oy=0;var a=this.TB.clone();j4(a,"RID","rpc");j4(a,"SID",this.B);j4(a,"CI",this.bw?"0":"1");j4(a,"AID",this.jp);g5(this,a);if(!g.ze||g.ae(10))j4(a,"TYPE","xmlhttp"),P4(this.ae,a,!0,this.au,!1);else{j4(a,"TYPE","html");var b=this.ae,c=!!this.au;b.Yp=3;b.dl=k4(a.clone());MHa(b,c)}};
g.k.dG=function(a,b){if(0!=this.Ja&&(this.ae==a||this.sg==a))if(this.pj=a.qr,this.sg==a&&3==this.Ja)if(7<this.Wm){try{var c=this.D.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.ak){if(this.ae)if(this.ae.Qp+3E3<this.sg.Qp)i5(this),this.ae.cancel(),this.ae=null;else break a;k5(this);M4(19)}}else this.aE=c[1],0<this.aE-this.jp&&37500>c[2]&&this.bw&&0==this.vo&&!this.cn&&(this.cn=K4((0,g.z)(this.GN,this),6E3));else l5(this,11)}else b!=MJa.kV.u&&l5(this,11);else if(this.ae==
a&&i5(this),!g.qc(b)){c=this.D.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.jp=e[0];e=e[1];2==this.Ja?"c"==e[0]?(this.B=e[1],this.au=e[2],e=e[3],null!=e?this.Wm=e:this.Wm=6,this.Ja=3,this.If&&this.If.hC(),this.TB=c5(this,this.Hs()?this.au:null,this.ly),jIa(this)):"stop"==e[0]&&l5(this,7):3==this.Ja&&("stop"==e[0]?l5(this,7):"noop"!=e[0]&&this.If&&this.If.gC(e),this.vo=0)}}};
g.k.GN=function(){null!=this.cn&&(this.cn=null,this.ae.cancel(),this.ae=null,k5(this),M4(20))};
g.k.cu=function(a){if(this.ae==a){i5(this);this.ae=null;var b=2}else if(this.sg==a)this.sg=null,b=1;else return;this.pj=a.qr;if(0!=this.Ja)if(a.Ei)1==b?(b=L4,b.dispatchEvent(new $Ha(b,a.Hn?a.Hn.length:0,g.A()-a.Qp,this.Lo)),h5(this),this.C.length=0):jIa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.pj)){if(d=1==b)this.sg||this.sl||1==this.Ja||2<=this.Lo?d=!1:(this.sl=K4((0,g.z)(this.kG,this,a),kIa(this,this.Lo)),this.Lo++,d=!0);d=!(d||2==b&&k5(this))}if(d)switch(c){case 1:l5(this,
5);break;case 4:l5(this,10);break;case 3:l5(this,6);break;case 7:l5(this,12);break;default:l5(this,2)}}};
g.k.tJ=function(a){if(!g.ib(arguments,this.Ja))throw Error("Unexpected channel state: "+this.Ja);};
g.k.rR=function(a){a?M4(2):(M4(1),lIa(this,8))};
g.k.yx=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new Y4;a.ea=!1;return a};
g.k.isActive=function(){return!!this.If&&this.If.isActive(this)};
g.k.ni=function(a){var b=L4;b.dispatchEvent(new aIa(b,a))};
g.k.Hs=function(){return!(!g.ze||g.ae(10))};
g.k=mIa.prototype;g.k.hC=function(){};
g.k.gC=function(){};
g.k.fC=function(){};
g.k.ix=function(){};
g.k.SC=function(){return{}};
g.k.isActive=function(){return!0};g.k=nIa.prototype;g.k.isEmpty=function(){return g.jb(this.u)&&g.jb(this.B)};
g.k.clear=function(){this.u=[];this.B=[]};
g.k.contains=function(a){return g.ib(this.u,a)||g.ib(this.B,a)};
g.k.remove=function(a){var b=this.u;var c=(0,g.rBa)(b,a);0<=c?(g.lb(b,c),b=!0):b=!1;return b||g.nb(this.B,a)};
g.k.Yf=function(){for(var a=[],b=this.u.length-1;0<=b;--b)a.push(this.u[b]);var c=this.B.length;for(b=0;b<c;++b)a.push(this.B[b]);return a};g.Ua(m5,g.B);g.k=m5.prototype;g.k.UP=function(){this.Kf=Math.min(3E5,2*this.Kf);this.C();this.B&&this.start()};
g.k.start=function(){var a=this.Kf+15E3*Math.random();g.mn(this.u,a);this.B=g.A()+a};
g.k.stop=function(){this.u.stop();this.B=0};
g.k.isActive=function(){return this.u.isActive()};
g.k.reset=function(){this.u.stop();this.Kf=5E3};g.Ua(n5,mIa);g.k=n5.prototype;g.k.subscribe=function(a,b,c){return this.C.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.C.unsubscribe(a,b,c)};
g.k.Rf=function(a){return this.C.Rf(a)};
g.k.V=function(a,b){return this.C.V.apply(this.C,arguments)};
g.k.dispose=function(){this.W||(this.W=!0,g.ag(this.C),qIa(this),g.ag(this.B),this.B=null,this.X=function(){return""})};
g.k.ma=function(){return this.W};
g.k.connect=function(a,b,c){if(!this.u||2!=this.u.getState()){this.U="";this.B.stop();this.F=a||null;this.D=b||0;a=this.ba+"/test";b=this.ba+"/bind";var d=new f5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.da),e=this.u;e&&(e.If=null);d.If=this;this.u=d;o5(this);if(this.u){d=g.L("ID_TOKEN");var f=this.u.oj||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.u.oj=f}e?(3!=e.getState()&&0==gIa(e)||e.getState(),this.u.connect(a,b,this.I,e.B,e.jp)):c?this.u.connect(a,
b,this.I,c.sessionId,c.arrayId):this.u.connect(a,b,this.I)}};
g.k.sendMessage=function(a,b){var c={_sc:a};b&&g.Yb(c,b);this.B.isActive()||2==(this.u?this.u.getState():0)?this.K.push(c):p5(this)&&(o5(this),fIa(this.u,c))};
g.k.hC=function(){this.B.reset();this.F=null;this.D=0;if(this.K.length){var a=this.K;this.K=[];for(var b=0,c=a.length;b<c;++b)fIa(this.u,a[b])}this.V("handlerOpened")};
g.k.fC=function(a){var b=2==a&&401==this.u.pj;4==a||b||this.B.start();this.V("handlerError",a,b)};
g.k.ix=function(a){if(!this.B.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.K.push(d)}};
g.k.SC=function(){var a={v:2};this.U&&(a.gsessionid=this.U);0!=this.D&&(a.ui=""+this.D);0!=this.L&&(a.ui=""+this.L);this.F&&g.Yb(a,this.F);return a};
g.k.gC=function(a){"S"==a[0]?this.U=a[1]:"gracefulReconnect"==a[0]?(this.B.start(),dIa(this.u)):this.V("handlerMessage",new oIa(a[0],a[1]))};
g.k.Ev=function(a){(this.I.loungeIdToken=a)||this.B.stop();if(this.ga&&this.u){var b=this.u.oj||{};a?b["X-YouTube-LoungeId-Token"]=a:delete b["X-YouTube-LoungeId-Token"];this.u.oj=b}};
g.k.TQ=function(){this.B.isActive();0==gIa(this.u)&&this.connect(this.F,this.D)};q5.prototype.D=function(a,b,c,d){b?a(d):a({text:c.responseText})};
q5.prototype.C=function(a,b){a(Error("Request error: "+b.status))};
q5.prototype.F=function(a){a(Error("request timed out"))};var xIa=g.A(),t5=null,w5=Array(50),v5=-1,x5=!1;g.Ua(y5,g.N);y5.prototype.Sg=function(){return this.screens};
y5.prototype.contains=function(a){return!!v4(this.screens,a)};
y5.prototype.get=function(a){return a?w4(this.screens,a):null};
y5.prototype.info=function(a){u5(this.I,a)};g.u(z5,g.N);g.k=z5.prototype;g.k.start=function(){!this.u&&isNaN(this.fb)&&this.wG()};
g.k.stop=function(){this.u&&(this.u.abort(),this.u=null);isNaN(this.fb)||(g.Ho(this.fb),this.fb=NaN)};
g.k.ca=function(){this.stop();g.N.prototype.ca.call(this)};
g.k.wG=function(){this.fb=NaN;this.u=g.uq(r5(this.F,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:this.I},timeout:5E3,onSuccess:(0,g.z)(this.XK,this),onError:(0,g.z)(this.WK,this),onTimeout:(0,g.z)(this.YK,this)})};
g.k.XK=function(a,b){this.u=null;var c=b.screen||{};c.dialId=this.C;c.name=this.D;this.V("pairingComplete",new q4(c))};
g.k.WK=function(a){this.u=null;a.status&&404==a.status?this.B>=OJa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=OJa[this.B],this.fb=g.Fo((0,g.z)(this.wG,this),a),this.B++):this.V("pairingFailed",Error("Server error "+a.status))};
g.k.YK=function(){this.u=null;this.V("pairingFailed",Error("Server not responding"))};
var OJa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ua(B5,y5);g.k=B5.prototype;g.k.start=function(){A5(this)&&this.V("screenChange");!g.vu("yt-remote-lounge-token-expiration")&&BIa(this);g.Ho(this.u);this.u=g.Fo((0,g.z)(this.start,this),1E4)};
g.k.add=function(a,b){A5(this);yIa(this,a);C5(this,!1);this.V("screenChange");b(a);a.token||BIa(this)};
g.k.remove=function(a,b){var c=A5(this);AIa(this,a)&&(C5(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.k.Yv=function(a,b,c,d){var e=A5(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,C5(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.k.ca=function(){g.Ho(this.u);B5.Od.ca.call(this)};
g.k.dK=function(a){A5(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}C5(this,!b);b&&u5(this.I,"Missed "+b+" lounge tokens.")};
g.k.cK=function(a){u5(this.I,"Requesting lounge tokens failed: "+a)};g.u(E5,g.N);g.k=E5.prototype;g.k.start=function(){var a=parseInt(g.vu("yt-remote-fast-check-period")||"0",10);(this.D=g.A()-144E5<a?0:a)?H5(this):(this.D=g.A()+3E5,g.uu("yt-remote-fast-check-period",this.D),this.Zz())};
g.k.isEmpty=function(){return g.Rb(this.u)};
g.k.update=function(){D5("Updating availability on schedule.");var a=this.I(),b=g.Fb(this.u,function(c,d){return c&&!!w4(a,d)},this);
G5(this,b)};
g.k.ca=function(){g.Ho(this.C);this.C=NaN;this.B&&(this.B.abort(),this.B=null);g.N.prototype.ca.call(this)};
g.k.Zz=function(){g.Ho(this.C);this.C=NaN;this.B&&this.B.abort();var a=DIa(this);if(m4(a)){var b=r5(this.F,"/pairing/get_screen_availability");this.B=s5(this.F,b,{lounge_token:g.Lb(a).join(",")},(0,g.z)(this.EP,this,a),(0,g.z)(this.DP,this))}else G5(this,{}),H5(this)};
g.k.EP=function(a,b){this.B=null;var c=g.Lb(DIa(this));if(g.Ab(c,g.Lb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;G5(this,d);H5(this)}else this.Ed("Changing Screen set during request."),this.Zz()};
g.k.DP=function(a){this.Ed("Screen availability failed: "+a);this.B=null;H5(this)};
g.k.Ed=function(a){u5("OnlineScreenService",a)};g.Ua(I5,y5);g.k=I5.prototype;g.k.start=function(){this.B.start();this.u.start();this.screens.length&&(this.V("screenChange"),this.u.isEmpty()||this.V("onlineScreenChange"))};
g.k.add=function(a,b,c){this.B.add(a,b,c)};
g.k.remove=function(a,b,c){this.B.remove(a,b,c);this.u.update()};
g.k.Yv=function(a,b,c,d){this.B.contains(a)?this.B.Yv(a,b,c,d):(a="Updating name of unknown screen: "+a.name,u5(this.I,a),d(Error(a)))};
g.k.Sg=function(a){return a?this.screens:g.qb(this.screens,g.Me(this.C,function(b){return!this.contains(b)},this))};
g.k.bI=function(){return g.Me(this.Sg(!0),function(a){return!!this.u.u[a.id]},this)};
g.k.cI=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new z5(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(h){g.ag(f);d(J5(this,h))},this));
f.subscribe("pairingFailed",function(h){g.ag(f);e(h)});
f.start();return(0,g.z)(f.stop,f)};
g.k.TR=function(a,b,c,d){g.uq(r5(this.F,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:a},timeout:5E3,onSuccess:(0,g.z)(function(e,f){var h=new q4(f.screen||{});if(!h.name||HIa(this,h.name)){a:{var l=h.name;for(var m=2,n=b(l,m);HIa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}h.name=l}c(J5(this,h))},this),
onError:(0,g.z)(function(e){d(Error("pairing request failed: "+e.status))},this),
onTimeout:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.k.ca=function(){g.ag(this.B);g.ag(this.u);I5.Od.ca.call(this)};
g.k.jK=function(){JIa(this);this.V("screenChange");this.u.update()};
I5.prototype.dispose=I5.prototype.dispose;g.Ua(L5,g.N);g.k=L5.prototype;g.k.getScreen=function(){return this.C};
g.k.hg=function(a){this.ma()||(a&&N5(this,""+a),this.C=null,this.V("sessionScreen",null))};
g.k.info=function(a){u5(this.ga,a)};
g.k.eI=function(){return null};
g.k.lA=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){N5(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.ca=function(){this.lA("");L5.Od.ca.call(this)};g.u(O5,L5);g.k=O5.prototype;g.k.kA=function(a){if(this.B){if(this.B==a)return;N5(this,"Overriding cast session with new session object");RIa(this);this.ba=!1;this.U="unknown";this.B.removeUpdateListener(this.da);this.B.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.X)}this.B=a;this.B.addUpdateListener(this.da);this.B.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.X);NIa(this,"getMdxSessionStatus")};
g.k.kp=function(a){this.info("launchWithParams no-op for Cast: "+g.Qj(a))};
g.k.stop=function(){this.B?this.B.stop((0,g.z)(function(){this.hg()},this),(0,g.z)(function(){this.hg(Error("Failed to stop receiver app."))},this)):this.hg(Error("Stopping cast device without session."))};
g.k.lA=function(){};
g.k.ca=function(){this.info("disposeInternal");RIa(this);this.B&&(this.B.removeUpdateListener(this.da),this.B.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.X));this.B=null;L5.prototype.ca.call(this)};
g.k.pQ=function(a,b){if(!this.ma())if(b){var c=I4(b);if(g.Pa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Qj(c));switch(d){case "mdxSessionStatus":LIa(this,c);break;case "loungeToken":OIa(this,c);break;default:N5(this,"Unknown youtube message: "+d)}}else N5(this,"Unable to parse message.")}else N5(this,"No data in message.")};
g.k.jD=function(a,b,c,d){g.Ho(this.L);this.L=0;GIa(this.F,this.u.label,a,this.u.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(N5(this,"Screen "+a+" appears to be offline. "+d+" retries left."),this.L=g.Fo((0,g.z)(this.jD,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.eI=function(){return this.B};
g.k.UR=function(a){this.ma()||a||(N5(this,"Cast session died."),this.hg())};g.u(R5,L5);g.k=R5.prototype;g.k.kA=function(a){this.D=a;this.D.addUpdateListener(this.X)};
g.k.kp=function(a){this.W=a;this.K()};
g.k.stop=function(){this.B();this.B=g.Ka;g.Ho(this.I);this.D?this.D.stop((0,g.z)(this.hg,this,null),(0,g.z)(this.hg,this,"Failed to stop DIAL device.")):this.hg()};
g.k.ca=function(){this.B();this.B=g.Ka;g.Ho(this.I);this.D&&this.D.removeUpdateListener(this.X);this.D=null;L5.prototype.ca.call(this)};
g.k.aL=function(a){this.ma()||a||(N5(this,"DIAL session died."),this.B(),this.B=g.Ka,this.hg())};
g.k.Dy=function(a){this.U=u4();if(this.W){var b=new chrome.cast.DialLaunchResponse(!0,TIa(this));a(b);SIa(this)}else this.K=(0,g.z)(function(){g.Ho(this.I);this.K=g.Ka;this.I=NaN;var c=new chrome.cast.DialLaunchResponse(!0,TIa(this));a(c);SIa(this)},this),this.I=g.Fo((0,g.z)(function(){this.K()},this),100)};
g.k.AK=function(a,b,c){GIa(this.F,this.L.receiver.label,a,this.u.friendlyName,(0,g.z)(function(d){d&&d.token?(M5(this,d),b(new chrome.cast.DialLaunchResponse(!1))):this.Dy(b,c)},this),(0,g.z)(function(d){N5(this,"Failed to get DIAL screen: "+d);
this.Dy(b,c)},this))};g.u(S5,L5);S5.prototype.stop=function(){this.hg()};
S5.prototype.kA=function(){};
S5.prototype.kp=function(){g.Ho(this.B);this.B=NaN;var a=w4(this.F.Sg(),this.u.label);a?M5(this,a):this.hg(Error("No such screen"))};
S5.prototype.ca=function(){g.Ho(this.B);this.B=NaN;L5.prototype.ca.call(this)};g.u(T5,g.N);g.k=T5.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.L);this.U||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.z)(this.oP,this);c=new chrome.cast.ApiConfig(c,(0,g.z)(this.fG,this),f,d,e);c.customDialLaunchCallback=(0,g.z)(this.bO,this);chrome.cast.initialize(c,(0,g.z)(function(){this.ma()||
(chrome.cast.addReceiverActionListener(this.F),uIa(),this.B.subscribe("onlineScreenChange",(0,g.z)(this.dI,this)),this.C=VIa(this),chrome.cast.setCustomReceivers(this.C,g.Ka,(0,g.z)(function(h){this.Ed("Failed to set initial custom receivers: "+g.Qj(h))},this)),this.V("yt-remote-cast2-availability-change",V5(this)),b(!0))},this),(0,g.z)(function(h){this.Ed("Failed to initialize API: "+g.Qj(h));
b(!1)},this))};
g.k.ZQ=function(a,b){U5("Setting connected screen ID: "+a+" -> "+b);if(this.u){var c=this.u.getScreen();if(!a||c&&c.id!=a)U5("Unsetting old screen status: "+this.u.u.friendlyName),W5(this,null)}if(a&&b){if(!this.u){c=w4(this.B.Sg(),a);if(!c){U5("setConnectedScreenStatus: Unknown screen.");return}if("shortLived"==c.idType){U5("setConnectedScreenStatus: Screen with id type to be short lived.");return}var d=UIa(this,c);d||(U5("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?
c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.C.push(d),chrome.cast.setCustomReceivers(this.C,g.Ka,(0,g.z)(function(e){this.Ed("Failed to set initial custom receivers: "+g.Qj(e))},this)));
U5("setConnectedScreenStatus: new active receiver: "+d.friendlyName);W5(this,new S5(this.B,d),!0)}this.u.lA(b)}else U5("setConnectedScreenStatus: no screen.")};
g.k.aR=function(a){this.ma()?this.Ed("Setting connection data on disposed cast v2"):this.u?this.u.kp(a):this.Ed("Setting connection data without a session")};
g.k.WR=function(){this.ma()?this.Ed("Stopping session on disposed cast v2"):this.u?(this.u.stop(),W5(this,null)):U5("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.z)(this.fG,this),(0,g.z)(this.GP,this))};
g.k.ca=function(){this.B.unsubscribe("onlineScreenChange",(0,g.z)(this.dI,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.F);var a=rIa,b=g.Ja("yt.mdx.remote.debug.handlers_");g.nb(b||[],a);g.ag(this.u);g.N.prototype.ca.call(this)};
g.k.Ed=function(a){u5("Controller",a)};
g.k.hG=function(a,b){this.u==a&&(b||W5(this,null),this.V("yt-remote-cast2-session-change",b))};
g.k.lP=function(a,b){if(!this.ma())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),U5("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.u)if(this.u.u.label!=a.label)U5("onReceiverAction_: Stopping active receiver: "+this.u.u.friendlyName),this.u.stop();else{U5("onReceiverAction_: Casting to active receiver.");this.u.getScreen()&&this.V("yt-remote-cast2-session-change",this.u.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:W5(this,
new S5(this.B,a));break;case chrome.cast.ReceiverType.DIAL:W5(this,new R5(this.B,a,this.K));break;case chrome.cast.ReceiverType.CAST:W5(this,new O5(this.B,a,this.D));break;default:this.Ed("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.u&&this.u.u.label==a.label?this.u.stop():this.Ed("Stopping receiver w/o session: "+a.friendlyName)}else this.Ed("onReceiverAction_ called without receiver.")};
g.k.bO=function(a){if(this.ma())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Ed("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.u?this.u.u:null;if(!c||c.label!=b.label)return this.Ed("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.u.getScreen())return U5("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.u.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Ed('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);W5(this,new R5(this.B,b,this.K))}b=this.u;b.L=a;return b.L.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.z)(b.AK,b,(b.L.extraData||{}).screenId||null)):new Promise((0,g.z)(b.Dy,b))};
g.k.fG=function(a){if(!this.ma()){U5("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.u)if(b.receiverType==chrome.cast.ReceiverType.CAST)U5("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),W5(this,new O5(this.B,b,this.D),!0);else{this.Ed("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.u.u,d=w4(this.B.Sg(),c.label);d&&r4(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(U5("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.ag(this.u),this.u=new O5(this.B,b,this.D),this.u.subscribe("sessionScreen",(0,g.z)(this.hG,this,this.u)),this.u.kp(null));this.u.kA(a)}}};
g.k.VR=function(){return this.u?this.u.eI():null};
g.k.GP=function(a){this.ma()||(this.Ed("Failed to estabilish a session: "+g.Qj(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&W5(this,null))};
g.k.oP=function(a){U5("Receiver availability updated: "+a);if(!this.ma()){var b=V5(this);this.I=a==chrome.cast.ReceiverAvailability.AVAILABLE;V5(this)!=b&&this.V("yt-remote-cast2-availability-change",V5(this))}};
g.k.dI=function(){this.ma()||(this.C=VIa(this),U5("Updating custom receivers: "+g.Qj(this.C)),chrome.cast.setCustomReceivers(this.C,g.Ka,(0,g.z)(function(){this.Ed("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",V5(this)))};
T5.prototype.setLaunchParams=T5.prototype.aR;T5.prototype.setConnectedScreenStatus=T5.prototype.ZQ;T5.prototype.stopSession=T5.prototype.WR;T5.prototype.getCastSession=T5.prototype.VR;T5.prototype.requestSession=T5.prototype.requestSession;T5.prototype.init=T5.prototype.init;T5.prototype.dispose=T5.prototype.dispose;var b6=[];g.k=g6.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";h6(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.u=a.trackData,this.rj=a.hasPrevious,this.hasNext=a.hasNext,this.L=a.playerTime,this.K=a.playerTimeAt,this.F=a.seekableStart,this.B=a.seekableEnd,this.I=a.duration,this.U=a.loadedTime,this.D=a.liveIngestionTime,this.C=!isNaN(this.D))};
g.k.Hb=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.C?this.I+i6(this):this.I};
g.k.clone=function(){return new g6(m6(this))};g.u(o6,g.N);g.k=o6.prototype;g.k.getState=function(){return this.Ja};
g.k.play=function(){q6(this)?(this.u?this.u.play(null,g.Ka,v6(this,"play")):u6(this,"play"),t6(this,1,k6(p6(this))),this.V("remotePlayerChange")):r6(this,this.play)};
g.k.pause=function(){q6(this)?(this.u?this.u.pause(null,g.Ka,v6(this,"pause")):u6(this,"pause"),t6(this,2,k6(p6(this))),this.V("remotePlayerChange")):r6(this,this.pause)};
g.k.seekTo=function(a){if(q6(this)){if(this.u){var b=p6(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.Hb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Ka,v6(this,"seekTo",{newTime:a}))}else u6(this,"seekTo",{newTime:a});t6(this,3,a);this.V("remotePlayerChange")}else r6(this,g.Sa(this.seekTo,a))};
g.k.stop=function(){if(q6(this)){this.u?this.u.stop(null,g.Ka,v6(this,"stopVideo")):u6(this,"stopVideo");var a=p6(this);a.index=-1;a.videoId="";h6(a);s6(this,a);this.V("remotePlayerChange")}else r6(this,this.stop)};
g.k.setVolume=function(a,b){if(q6(this)){var c=p6(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.z)(function(){u5("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.Ed("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.z)(function(){u5("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.Ed("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);u6(this,"setVolume",e)}c.muted=b;c.volume=a;s6(this,c)}else r6(this,g.Sa(this.setVolume,a,b))};
g.k.aI=function(a,b){if(q6(this)){var c=p6(this),d={videoId:a};b&&(c.u={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Qj(b.style),g.Yb(d,c.u));u6(this,"setSubtitlesTrack",d);s6(this,c)}else r6(this,g.Sa(this.aI,a,b))};
g.k.setAudioTrack=function(a,b){if(q6(this)){var c=b.getLanguageInfo().getId();u6(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=p6(this);d.audioTrackId=c;s6(this,d)}else r6(this,g.Sa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=p6(this);c=c||0;var m={videoId:a,currentIndex:c};l6(l,a,c);void 0!==b&&(j6(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.Qj(h));u6(this,"setPlaylist",m);d||s6(this,l)};
g.k.kv=function(a,b){if(q6(this)){if(a&&b){var c=p6(this);l6(c,a,b);s6(this,c)}u6(this,"previous")}else r6(this,g.Sa(this.kv,a,b))};
g.k.nextVideo=function(a,b){if(q6(this)){if(a&&b){var c=p6(this);l6(c,a,b);s6(this,c)}u6(this,"next")}else r6(this,g.Sa(this.nextVideo,a,b))};
g.k.zC=function(){q6(this)?u6(this,"dismissAutoplay"):r6(this,this.zC)};
g.k.dispose=function(){if(3!=this.Ja){var a=this.Ja;this.Ja=3;this.V("proxyStateChange",a,this.Ja)}g.N.prototype.dispose.call(this)};
g.k.ca=function(){hJa(this);this.C=null;this.D.clear();n6(this,null);g.N.prototype.ca.call(this)};
g.k.oA=function(a){if((a!=this.Ja||2==a)&&3!=this.Ja&&0!=a){var b=this.Ja;this.Ja=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)b=a=this.D,g.jb(b.u)&&(b.u=b.B,b.u.reverse(),b.B=[]),a.u.pop().apply(this);else 3==a&&this.dispose()}};
g.k.iP=function(a,b){this.V(a,b)};
g.k.NN=function(a){if(!a)this.Xr(null),n6(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=p6(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)u5("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,s6(this,b)}};
g.k.Xr=function(a){u5("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.K);if(this.u=a)this.u.addUpdateListener(this.K),iJa(this),this.V("remotePlayerChange")};
g.k.MN=function(a){a?(iJa(this),this.V("remotePlayerChange")):this.Xr(null)};
g.k.DA=function(){u6(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.UN=function(){var a=eJa();a&&n6(this,a)};
g.k.Ed=function(a){u5("CP",a)};g.u(w6,g.N);g.k=w6.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.Jb.listId=c);this.Jb.videoId=d;this.Jb.index=h||0;this.Jb.state=3;j6(this.Jb,m);this.D="UNSUPPORTED";x6("Connecting with setPlaylist and params: "+g.Qj(l));this.u.connect({method:"setPlaylist",
params:g.Qj(l)},a,oHa())}else x6("Connecting without params"),this.u.connect({},a,oHa());kJa(this)};
g.k.Ev=function(a){this.u.Ev(a)};
g.k.dispose=function(){this.ma()||(this.V("beforeDispose"),y6(this,3));g.N.prototype.dispose.call(this)};
g.k.ca=function(){z6(this);B6(this);A6(this);g.Ho(this.K);this.K=NaN;g.Ho(this.L);this.L=NaN;this.C=null;g.hp(this.ba);this.ba.length=0;this.u.dispose();g.N.prototype.ca.call(this);this.D=this.I=this.B=this.Jb=this.u=null};
g.k.XJ=function(){this.Ho(2)};
g.k.RN=function(){x6("Channel opened");this.X&&(this.X=!1,A6(this),this.W=g.Fo((0,g.z)(function(){x6("Timing out waiting for a screen.");this.Ho(1)},this),15E3));
sHa(pIa(this.u),this.ga)};
g.k.ON=function(){x6("Channel closed");isNaN(this.F)?B4(!0):B4();this.dispose()};
g.k.PN=function(a,b){B4();isNaN(this.gr())?(b&&"shortLived"==this.da&&this.V("browserChannelAuthError",a),x6("Channel error: "+a+" without reconnection"),this.dispose()):(this.X=!0,x6("Channel error: "+a+" with reconnection in "+this.gr()+" ms"),y6(this,2))};
g.k.QN=function(a){a.params?x6("Received: action="+a.action+", params="+g.Qj(a.params)):x6("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=I4(a.params.devices);this.B=g.Oc(a,function(c){return new p4(c)});
a=!!g.eb(this.B,function(c){return"LOUNGE_SCREEN"==c.type});
nJa(this,a);break;case "loungeScreenDisconnected":g.pb(this.B,function(c){return"LOUNGE_SCREEN"==c.type});
nJa(this,!1);break;case "remoteConnected":var b=new p4(I4(a.params.device));g.eb(this.B,function(c){return b?c.id==b.id:!1})||ZGa(this.B,b);
break;case "remoteDisconnected":b=new p4(I4(a.params.device));g.pb(this.B,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":pJa(this,a);break;case "nowPlaying":rJa(this,a);break;case "onStateChange":qJa(this,a);break;case "onAdStateChange":sJa(this,a);break;case "onVolumeChanged":tJa(this,a);break;case "onSubtitlesTrackChanged":oJa(this,a);break;case "nowAutoplaying":uJa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.I=a.params.videoId||null;this.V("autoplayUpNext",this.I);break;case "onAutoplayModeChanged":this.D=
a.params.autoplayMode;this.V("autoplayModeChange",this.D);"DISABLED"==this.D&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":vJa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:x6("Unrecognized action: "+a.action)}};
g.k.PQ=function(){if(this.C){var a=this.C;this.C=null;this.Jb.videoId!=a&&C6(this,"getNowPlaying")}};
g.k.OJ=function(){var a=3;this.ma()||(a=0,isNaN(this.gr())?p5(this.u)&&isNaN(this.F)&&(a=1):a=2);return a};
g.k.Ho=function(a){x6("Disconnecting with "+a);z6(this);this.V("beforeDisconnect",a);1==a&&B4();qIa(this.u,a);this.dispose()};
g.k.MJ=function(){var a=this.Jb;this.C&&(a=this.Jb.clone(),l6(a,this.C,a.index));return m6(a)};
g.k.bR=function(a){var b=new g6(a);b.videoId&&b.videoId!=this.Jb.videoId&&(this.C=b.videoId,g.Ho(this.K),this.K=g.Fo((0,g.z)(this.PQ,this),5E3));var c=[];this.Jb.listId==b.listId&&this.Jb.videoId==b.videoId&&this.Jb.index==b.index||c.push("remoteQueueChange");this.Jb.playerState==b.playerState&&this.Jb.volume==b.volume&&this.Jb.muted==b.muted&&k6(this.Jb)==k6(b)&&g.Qj(this.Jb.u)==g.Qj(b.u)||c.push("remotePlayerChange");this.Jb.reset(a);g.Cb(c,function(d){this.V(d)},this)};
g.k.iD=function(){var a=this.u.I.id,b=g.eb(this.B,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.gr=function(){var a=this.u;return a.B.isActive()?a.B.B-g.A():NaN};
g.k.DJ=function(){return this.D||"UNSUPPORTED"};
g.k.EJ=function(){return this.I||""};
g.k.SR=function(){if(!isNaN(this.gr())){var a=this.u.B;g.nn(a.u);a.start()}};
g.k.XQ=function(a,b){C6(this,a,b);mJa(this)};
g.k.ZH=function(){var a=g.Bq("SID","")||"",b=g.Bq("SAPISID","")||"",c=g.Bq("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.uf(g.Xe(a),2);b=g.uf(g.Xe(b),2);c=g.uf(g.Xe(c),2);return g.uf(g.Xe(a+","+b+","+c),2)};
w6.prototype.subscribe=w6.prototype.subscribe;w6.prototype.unsubscribeByKey=w6.prototype.Rf;w6.prototype.getProxyState=w6.prototype.OJ;w6.prototype.disconnect=w6.prototype.Ho;w6.prototype.getPlayerContextData=w6.prototype.MJ;w6.prototype.setPlayerContextData=w6.prototype.bR;w6.prototype.getOtherConnectedRemoteId=w6.prototype.iD;w6.prototype.getReconnectTimeout=w6.prototype.gr;w6.prototype.getAutoplayMode=w6.prototype.DJ;w6.prototype.getAutoplayVideoId=w6.prototype.EJ;w6.prototype.reconnect=w6.prototype.SR;
w6.prototype.sendMessage=w6.prototype.XQ;w6.prototype.getXsrfToken=w6.prototype.ZH;g.u(D6,y5);g.k=D6.prototype;g.k.Sg=function(a){return this.Jf.$_gs(a)};
g.k.contains=function(a){return!!this.Jf.$_c(a)};
g.k.get=function(a){return this.Jf.$_g(a)};
g.k.start=function(){this.Jf.$_st()};
g.k.add=function(a,b,c){this.Jf.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Jf.$_r(a,b,c)};
g.k.Yv=function(a,b,c,d){this.Jf.$_un(a,b,c,d)};
g.k.ca=function(){for(var a=0,b=this.u.length;a<b;++a)this.Jf.$_ubk(this.u[a]);this.u.length=0;this.Jf=null;y5.prototype.ca.call(this)};
g.k.ZK=function(){this.V("screenChange")};
g.k.PO=function(){this.V("onlineScreenChange")};
I5.prototype.$_st=I5.prototype.start;I5.prototype.$_gspc=I5.prototype.TR;I5.prototype.$_gsppc=I5.prototype.cI;I5.prototype.$_c=I5.prototype.contains;I5.prototype.$_g=I5.prototype.get;I5.prototype.$_a=I5.prototype.add;I5.prototype.$_un=I5.prototype.Yv;I5.prototype.$_r=I5.prototype.remove;I5.prototype.$_gs=I5.prototype.Sg;I5.prototype.$_gos=I5.prototype.bI;I5.prototype.$_s=I5.prototype.subscribe;I5.prototype.$_ubk=I5.prototype.Rf;var Q6=null,W6=!1,E6=null,F6=null,V6=null,J6=[];g.u(X6,g.B);g.k=X6.prototype;g.k.ca=function(){g.B.prototype.ca.call(this);this.u.stop();this.C.stop();this.L.stop();this.X();var a=this.ub;a.unsubscribe("proxyStateChange",this.cG,this);a.unsubscribe("remotePlayerChange",this.ks,this);a.unsubscribe("remoteQueueChange",this.gv,this);a.unsubscribe("previousNextChange",this.ZF,this);a.unsubscribe("nowAutoplaying",this.UF,this);a.unsubscribe("autoplayDismissed",this.sF,this);this.ub=this.B=null};
g.k.JE=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.ub.Ja)if(Y6(this)){if(!p6(this.ub).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":p6(this.ub).Hb()?this.ub.pause():this.ub.play();break;case "control_play":this.ub.play();break;case "control_pause":this.ub.pause();break;case "control_seek":this.K.tE(c[0],c[1]);break;case "control_subtitles_set_track":Z6(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.J.getCurrentTime();$6(this,0===c?void 0:c);break;case "control_seek":$6(this,c[0]);break;case "control_subtitles_set_track":Z6(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.KN=function(a){this.L.UJ(a)};
g.k.HR=function(a){this.JE("control_subtitles_set_track",g.Rb(a)?null:a)};
g.k.rH=function(){var a=this.J.getOption("captions","track");g.Rb(a)||Z6(this,a)};
g.k.Cb=function(a){this.B.Cb(a,this.J.getVideoData().lengthSeconds)};
g.k.yO=function(){g.Rb(this.D)||GJa(this,this.D);this.F=!1};
g.k.cG=function(a,b){this.C.stop();2===b&&this.oH()};
g.k.ks=function(){if(Y6(this)){this.u.stop();var a=p6(this.ub);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.B.Ne=1;break;case 1082:case 1083:this.B.Ne=0;break;default:this.B.Ne=-1}switch(a.playerState){case 1081:case 1:this.sb(new g.VK(8));this.nH();break;case 1085:case 3:this.sb(new g.VK(9));break;case 1083:case 0:this.sb(new g.VK(2));this.K.stop();this.Cb(this.J.getVideoData().lengthSeconds);break;case 1084:this.sb(new g.VK(4));break;case 2:this.sb(new g.VK(4));this.Cb(k6(a));
break;case -1:this.sb(new g.VK(64));break;case -1E3:this.sb(new g.VK(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=p6(this.ub).u;var b=this.D;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.D=a,GJa(this,a));a=p6(this.ub);-1===a.volume||Math.round(this.J.getVolume())===a.volume&&this.J.isMuted()===a.muted||this.U.isActive()||this.PH()}else FJa(this)};
g.k.ZF=function(){this.J.V("mdxpreviousnextchange")};
g.k.gv=function(){Y6(this)||FJa(this)};
g.k.UF=function(a){isNaN(a)||this.J.V("mdxnowautoplaying",a)};
g.k.sF=function(){this.J.V("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){Y6(this)&&this.ub.setAudioTrack(this.J.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===p6(this.ub).playerState?$6(this,a):b&&this.ub.seekTo(a)};
g.k.PH=function(){var a=this;if(Y6(this)){var b=p6(this.ub);this.events.Kb(this.W);b.muted?this.J.mute():this.J.unMute();this.J.setVolume(b.volume);this.W=this.events.P(this.J,"onVolumeChange",function(c){EJa(a,c)})}};
g.k.nH=function(){this.u.stop();if(!this.ub.ma()){var a=p6(this.ub);a.Hb()&&this.sb(new g.VK(8));this.Cb(k6(a));this.u.start()}};
g.k.oH=function(){this.C.stop();this.u.stop();var a=this.ub.C.getReconnectTimeout();2==this.ub.Ja&&!isNaN(a)&&this.C.start()};
g.k.sb=function(a){this.C.stop();var b=this.I;if(!g.$K(b,a)){var c=g.T(a,2);c!==g.T(this.I,2)&&this.J.Kn(c);this.I=a;IJa(this.B,b,a)}};g.u(a7,g.U);a7.prototype.Dc=function(){this.u.show()};
a7.prototype.jb=function(){this.u.hide()};
a7.prototype.B=function(){g.AK("https://support.google.com/youtube/answer/7640706")};
a7.prototype.C=function(){o4("mdx-manual-pairing-popup-ok");this.jb()};g.u(b7,g.U);b7.prototype.Dc=function(){this.u.show()};
b7.prototype.jb=function(){this.u.hide()};
b7.prototype.B=function(){o4("mdx-privacy-popup-cancel");this.jb()};
b7.prototype.C=function(){o4("mdx-privacy-popup-confirm");this.jb()};g.u(c7,g.U);c7.prototype.B=function(a){HJa(this,a.state)};g.u(d7,g.AR);d7.prototype.D=function(){var a=this.J.getOption("remote","receivers");a&&1<a.length&&!this.J.getOption("remote","quickCast")?(this.fm=g.Db(a,this.u,this),g.BR(this,g.Oc(a,this.u)),a=this.J.getOption("remote","currentReceiver"),a=this.u(a),this.options[a]&&this.Ah(a),this.enable(!0)):this.enable(!1)};
d7.prototype.u=function(a){return a.key};
d7.prototype.li=function(a){return"cast-selector-receiver"===a?"Cast...":this.fm[a].name};
d7.prototype.jf=function(a){g.AR.prototype.jf.call(this,a);this.J.setOption("remote","currentReceiver",this.fm[a]);this.Xa.jb()};g.u(e7,g.nO);g.k=e7.prototype;
g.k.create=function(){var a=this.player.S(),b=g.GD(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:g.P(a.experiments,"mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:g.P(a.experiments,"enable_dial_short_lived_lounge_token"),enableCastLoungeToken:g.P(a.experiments,"enable_cast_short_lived_lounge_token")};zJa(b,a);this.subscriptions.push(g.Mo("yt-remote-before-disconnect",this.IN,this));this.subscriptions.push(g.Mo("yt-remote-connection-change",this.pP,this));this.subscriptions.push(g.Mo("yt-remote-receiver-availability-change",
this.bG,this));this.subscriptions.push(g.Mo("yt-remote-auto-connect",this.nP,this));this.subscriptions.push(g.Mo("yt-remote-receiver-resumed",this.mP,this));this.subscriptions.push(g.Mo("mdx-privacy-popup-confirm",this.EQ,this));this.subscriptions.push(g.Mo("mdx-privacy-popup-cancel",this.DQ,this));this.subscriptions.push(g.Mo("mdx-manual-pairing-popup-ok",this.SK,this));this.bG()};
g.k.load=function(){this.player.cancelPlayback();g.nO.prototype.load.call(this);this.mh=new X6(this,this.player,this.ub);var a=(a=DJa())?a.currentTime:0;var b=U6()?new o6(O6(),void 0):null;0==a&&b&&(a=k6(p6(b)));0!==a&&this.Cb(a);IJa(this,this.Nc,this.Nc);this.player.Sj(6)};
g.k.unload=function(){this.player.V("mdxautoplaycanceled");this.nl=this.ii;g.bg(this.mh,this.ub);this.ub=this.mh=null;g.nO.prototype.unload.call(this);this.player.Sj(5);f7(this)};
g.k.ca=function(){g.No(this.subscriptions);g.nO.prototype.ca.call(this)};
g.k.Jj=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.mh.JE.apply(this.mh,[a].concat(g.ma(c)))};
g.k.getAdState=function(){return this.Ne};
g.k.PJ=function(){return this.loaded?this.mh.suggestion:null};
g.k.rj=function(){return this.ub?p6(this.ub).rj:!1};
g.k.hasNext=function(){return this.ub?p6(this.ub).hasNext:!1};
g.k.Cb=function(a,b){this.bE=a||0;this.player.V("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.bE};
g.k.getProgressState=function(){var a=p6(this.ub),b=this.player.getVideoData();return{allowSeeking:g.P(this.player.S().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Le():!a.isAdPlaying()&&this.player.Le(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.D+i6(a):a.D,isAtLiveHead:1>=(a.C?a.B+i6(a):a.B)-this.getCurrentTime(),loaded:a.U,seekableEnd:a.C?a.B+i6(a):a.B,seekableStart:0<a.F?a.F+
i6(a):a.F}};
g.k.nextVideo=function(){this.ub&&this.ub.nextVideo()};
g.k.kv=function(){this.ub&&this.ub.kv()};
g.k.IN=function(a){1===a&&(this.Oz=this.ub?p6(this.ub):null)};
g.k.pP=function(){var a=U6()?new o6(O6(),void 0):null;if(a){var b=this.nl;this.loaded&&this.unload();this.ub=a;this.Oz=null;b.key!==this.ii.key&&(this.nl=b,this.load())}else g.ag(this.ub),this.ub=null,this.loaded&&(this.unload(),(a=this.Oz)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,k6(a)));this.player.V("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.bG=function(){var a=[this.ii],b=a.concat,c=AJa();c6()&&g.vu("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.fm=b.call(a,c);a=P6()||this.ii;g7(this,a);this.player.ua("onMdxReceiversChange")};
g.k.nP=function(){var a=P6();g7(this,a)};
g.k.mP=function(){this.nl=P6()};
g.k.EQ=function(){this.qs=!0;f7(this);W6=!1;Q6&&S6(Q6,1);Q6=null};
g.k.DQ=function(){this.qs=!1;f7(this);g7(this,this.ii);this.nl=this.ii;W6=!1;Q6=null;this.player.playVideo()};
g.k.SK=function(){this.yu=!0;f7(this);g.uu("yt-remote-manual-pairing-warning-shown",!0,2592E3);W6=!1;Q6&&S6(Q6,1);Q6=null};
g.k.Fe=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.fm;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?e6():g7(this,b)),this.loaded?this.nl:this.ii;case "quickCast":return 2===this.fm.length&&"cast-selector-receiver"===this.fm[1].key?(b&&e6(),!0):!1}};
g.k.DA=function(){this.ub.DA()};
g.k.Ci=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.tO.remote=e7;})(_yt_player);
